\c "RW_NBDC" 
CREATE EXTENSION dblink;
\c "RB_CARCA_NP_RBPULSE" 
CREATE EXTENSION dblink;
\c "RB_PAK_IMS_HC" 
CREATE EXTENSION dblink;
\c "RB_PAK_NEWSPAGE_HC" 
CREATE EXTENSION dblink;
\c "RBPULSE_PAK" 
CREATE EXTENSION dblink;
\c "RB_BRAZIL_MFA_NEWSPAGE" 
CREATE EXTENSION dblink;
\c "RB_TURKEY_RBPULSE" 
CREATE EXTENSION dblink;
\c "RB_BRAZIL_IMS" 
CREATE EXTENSION dblink;
\c "RB_VN_DKSH_RBPULSE" 
CREATE EXTENSION dblink;
\c "RB_VN_RBPULSE" 
CREATE EXTENSION dblink;
\c "RB_CHILE_NP_RBPULSE" 
CREATE EXTENSION dblink;
\c "RB_CHILE_RBPULSE" 
CREATE EXTENSION dblink;
\c "RB_COL_NP_RBPULSE" 
CREATE EXTENSION dblink;
\c "RB_COL_RBPULSE" 
CREATE EXTENSION dblink;
\c "RB_IRE_UDD_HEALTH" 
CREATE EXTENSION dblink;
\c "RB_IRELAND_RBPULSE" 
CREATE EXTENSION dblink;
\c "RB_BRA_RBONE" 
CREATE EXTENSION dblink;
\c "RB_PER_ECU_NP_RBPULSE" 
CREATE EXTENSION dblink;
\c "RB_APAC_LM" 
CREATE EXTENSION dblink;
\c "BACARDI_MY" 
CREATE EXTENSION dblink;
\c "BACARDI_SEA" 
CREATE EXTENSION dblink;
\c "RW_BYIMANA" 
CREATE EXTENSION dblink;
\c "RW_NSABEFAMILY" 
CREATE EXTENSION dblink;
\c "RW_SOVES" 
CREATE EXTENSION dblink;
\c "RW_NTAFACO" 
CREATE EXTENSION dblink;
\c "BACARDI_MR_RENOUVO" 
CREATE EXTENSION dblink;
\c "INTEL" 
CREATE EXTENSION dblink;
\c "LOREAL_COMPETITRACK" 
CREATE EXTENSION dblink;
\c "ADIDAS_EM" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER10" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER_1" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER4" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER2" 
CREATE EXTENSION dblink;
\c "DIAGEO_COAST" 
CREATE EXTENSION dblink;
\c "DIAGEO_NILWA" 
CREATE EXTENSION dblink;
\c "DIAGEO_CLG" 
CREATE EXTENSION dblink;
\c "DIAGEO_WLG" 
CREATE EXTENSION dblink;
\c "DIAGEO_CASAMA" 
CREATE EXTENSION dblink;
\c "DIAGEO_PROOF" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER15" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER16" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER53" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER54" 
CREATE EXTENSION dblink;
\c "DIAGEO_ILG" 
CREATE EXTENSION dblink;
\c "DIAGEO_ALM" 
CREATE EXTENSION dblink;
\c "DIAGEO" 
CREATE EXTENSION dblink;
\c "DIAGEO_DANMURPHYS" 
CREATE EXTENSION dblink;
\c "GO_SPORTS" 
CREATE EXTENSION dblink;
\c "RSH" 
CREATE EXTENSION dblink;
\c "BACARDI_SAPPORO" 
CREATE EXTENSION dblink;
\c "BACARDI_MMI" 
CREATE EXTENSION dblink;
\c "BACARDI_FATTAL" 
CREATE EXTENSION dblink;
\c "BACARDI" 
CREATE EXTENSION dblink;
\c "RL_US_SUBSCRIBER" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER11" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER17" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER20" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER23" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER25" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER27" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER29" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER30" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER32" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER33" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER41" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER42" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER43" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER44" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER45" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER46" 
CREATE EXTENSION dblink;
\c "CARLSBERG_UK" 
CREATE EXTENSION dblink;
\c "ABOUT_YOU_GMBH" 
CREATE EXTENSION dblink;
\c "AMAZON_EU_SARL" 
CREATE EXTENSION dblink;
\c "DEVIANNE" 
CREATE EXTENSION dblink;
\c "LOREAL_VALASSIS_DIGITAL" 
CREATE EXTENSION dblink;
\c "BACARDI_FTI" 
CREATE EXTENSION dblink;
\c "BACARDI_ALCHEMY" 
CREATE EXTENSION dblink;
\c "LOREAL_MARKETTRACK" 
CREATE EXTENSION dblink;
\c "FASHION_COMPANY" 
CREATE EXTENSION dblink;
\c "LA_REDOUTE_SA" 
CREATE EXTENSION dblink;
\c "LE_BON_MARCHE" 
CREATE EXTENSION dblink;
\c "OTTO_VERSAND_GMBH" 
CREATE EXTENSION dblink;
\c "PROFIDA_SA" 
CREATE EXTENSION dblink;
\c "PUBLIKAT_GMBH" 
CREATE EXTENSION dblink;
\c "ULTRA_JEANS_LTD" 
CREATE EXTENSION dblink;
\c "URBAN_OUTFITTERS" 
CREATE EXTENSION dblink;
\c "VOICE_NORGE" 
CREATE EXTENSION dblink;
\c "RETAILERS_US" 
CREATE EXTENSION dblink;
\c "LOREAL_NIELSEN" 
CREATE EXTENSION dblink;
\c "LOREAL_AMAZON" 
CREATE EXTENSION dblink;
\c "CARLSBERG" 
CREATE EXTENSION dblink;
\c "LOREAL_LOREALDW" 
CREATE EXTENSION dblink;
\c "LEVI" 
CREATE EXTENSION dblink;
\c "LOREAL_VALASSIS_FSI" 
CREATE EXTENSION dblink;
\c "LOREAL_NCH" 
CREATE EXTENSION dblink;
\c "TEMCMSTDSUB_MPM1_3" 
CREATE EXTENSION dblink;
\c "MERCK" 
CREATE EXTENSION dblink;
\c "TEMCMSTDPUB" 
CREATE EXTENSION dblink;
\c "LOREAL_CVS" 
CREATE EXTENSION dblink;
\c "RL" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER6" 
CREATE EXTENSION dblink;
\c "RL_PUBLISHER5" 
CREATE EXTENSION dblink;
\c "LUISA_VIA_ROMA" 
CREATE EXTENSION dblink;
\c "EPI" 
CREATE EXTENSION dblink;
\c "FREETIME" 
CREATE EXTENSION dblink;
\c "SPORTS_ENDEAVORS_INC" 
CREATE EXTENSION dblink;
\c "END" 
CREATE EXTENSION dblink;
\c "ONE_BLOCK_DOWN" 
CREATE EXTENSION dblink;
\c "NIKE_ADMIN" 
CREATE EXTENSION dblink;
\c "FOOTASYLUM" 
CREATE EXTENSION dblink;
\c "OFFICE" 
CREATE EXTENSION dblink;
\c "SPORT_2000_FRANCE" 
CREATE EXTENSION dblink;
\c "ASOS_UK" 
CREATE EXTENSION dblink;
\c "DEICHMANN_GROUP" 
CREATE EXTENSION dblink;
\c "FANATICS" 
CREATE EXTENSION dblink;
\c "SPORT_2000_GERMANY" 
CREATE EXTENSION dblink;
\c "CROSS_TRAINER" 
CREATE EXTENSION dblink;
\c "TFG" 
CREATE EXTENSION dblink;
\c "SPORTMAS_RETAILERS" 
CREATE EXTENSION dblink;
\c "CHELSEA" 
CREATE EXTENSION dblink;
\c "DODENHOF" 
CREATE EXTENSION dblink;
\c "KING" 
CREATE EXTENSION dblink;
\c "SARENZA_CONVERSE" 
CREATE EXTENSION dblink;
\c "KOREA1" 
CREATE EXTENSION dblink;
\c "KOREA2" 
CREATE EXTENSION dblink;
\c "KOREA3" 
CREATE EXTENSION dblink;
\c "NIKE" 
CREATE EXTENSION dblink;
\c "KOREA4" 
CREATE EXTENSION dblink;
\c "FOOTLOCKER_US" 
CREATE EXTENSION dblink;
\c "JD_SPORTS_AUSTRALIA" 
CREATE EXTENSION dblink;
\c "THE_ICONIC" 
CREATE EXTENSION dblink;
\c "SPORTS_CHECK" 
CREATE EXTENSION dblink;
\c "SPORTMASTER" 
CREATE EXTENSION dblink;
\c "NIKE_KOREA" 
CREATE EXTENSION dblink;
\c "TENNIS_POINT" 
CREATE EXTENSION dblink;
\c "ELVERYS" 
CREATE EXTENSION dblink;
\c "SPORTSHOP_DIRECT" 
CREATE EXTENSION dblink;
\c "PRO_DIRECT_UK" 
CREATE EXTENSION dblink;
\c "PRO_DIRECT_US" 
CREATE EXTENSION dblink;
\c "FOOTASYLUM_CONVERSE" 
CREATE EXTENSION dblink;
\c "TEXT" 
CREATE EXTENSION dblink;
\c "QUEST" 
CREATE EXTENSION dblink;
\c "GALLERY2" 
CREATE EXTENSION dblink;
\c "HIMARAYA" 
CREATE EXTENSION dblink;
\c "XEBIO" 
CREATE EXTENSION dblink;
\c "ABCMART_JP" 
CREATE EXTENSION dblink;
\c "ALPEN" 
CREATE EXTENSION dblink;
\c "KAMO" 
CREATE EXTENSION dblink;
\c "NIKE_TW" 
CREATE EXTENSION dblink;
\c "NIKE_HK" 
CREATE EXTENSION dblink;
\c "HADDAD" 
CREATE EXTENSION dblink;
\c "AOLONGSHIBO" 
CREATE EXTENSION dblink;
\c "GOODBABY" 
CREATE EXTENSION dblink;
\c "INTERSPORT" 
CREATE EXTENSION dblink;
\c "JIEZHIXING" 
CREATE EXTENSION dblink;
\c "HIGHWAVE_SPORTS" 
CREATE EXTENSION dblink;
\c "POUSHENG" 
CREATE EXTENSION dblink;
\c "QD_BOCHENG" 
CREATE EXTENSION dblink;
\c "REALLY" 
CREATE EXTENSION dblink;
\c "SANSE" 
CREATE EXTENSION dblink;
\c "SHAANXI_LIHE" 
CREATE EXTENSION dblink;
\c "SHUANGJIAN" 
CREATE EXTENSION dblink;
\c "XIE_WAN_KU" 
CREATE EXTENSION dblink;
\c "YN_YUCHENG" 
CREATE EXTENSION dblink;
\c "SPORTAMORE" 
CREATE EXTENSION dblink;
\c "DF_SPORT" 
CREATE EXTENSION dblink;
\c "SPORTLER" 
CREATE EXTENSION dblink;
\c "SPORTLAND" 
CREATE EXTENSION dblink;
\c "FCBM" 
CREATE EXTENSION dblink;
\c "ON_THE_RUN" 
CREATE EXTENSION dblink;
\c "STIRLING_SPORTS" 
CREATE EXTENSION dblink;
\c "MAXI_SPORT_SPACE23" 
CREATE EXTENSION dblink;
\c "STUDIO_88" 
CREATE EXTENSION dblink;
\c "ITS_FINLAND" 
CREATE EXTENSION dblink;
\c "YOOX" 
CREATE EXTENSION dblink;
\c "SCHUSTER" 
CREATE EXTENSION dblink;
\c "JELMOLI" 
CREATE EXTENSION dblink;
\c "MISTER_TENNIS" 
CREATE EXTENSION dblink;
\c "SPORT_24" 
CREATE EXTENSION dblink;
\c "JOANIN" 
CREATE EXTENSION dblink;
\c "GRESVIG" 
CREATE EXTENSION dblink;
\c "SPRINTER" 
CREATE EXTENSION dblink;
\c "WIT" 
CREATE EXTENSION dblink;
\c "PTMAA" 
CREATE EXTENSION dblink;
\c "INTERSPORT_AUSTRIA" 
CREATE EXTENSION dblink;
\c "INTERSPORT_DENMARK" 
CREATE EXTENSION dblink;
\c "UNISPORT_AS" 
CREATE EXTENSION dblink;
\c "PSGM" 
CREATE EXTENSION dblink;
\c "I_RUN" 
CREATE EXTENSION dblink;
\c "B4B" 
CREATE EXTENSION dblink;
\c "EURETCO" 
CREATE EXTENSION dblink;
\c "SEA_RETAILERS" 
CREATE EXTENSION dblink;
\c "SPORT1" 
CREATE EXTENSION dblink;
\c "KICKZ" 
CREATE EXTENSION dblink;
\c "FOOT_LOCKER_US" 
CREATE EXTENSION dblink;
\c "MARTI" 
CREATE EXTENSION dblink;
\c "KOHLS" 
CREATE EXTENSION dblink;
\c "NORDSTROM" 
CREATE EXTENSION dblink;
\c "H_BATTA" 
CREATE EXTENSION dblink;
\c "ZSUPER" 
CREATE EXTENSION dblink;
\c "LIVERPOOL" 
CREATE EXTENSION dblink;
\c "PALACIO" 
CREATE EXTENSION dblink;
\c "INNOVA" 
CREATE EXTENSION dblink;
\c "NIKE_DO_BRASIL_NFS" 
CREATE EXTENSION dblink;
\c "NIKE_DO_BRASIL_NIKECOM" 
CREATE EXTENSION dblink;
\c "TAF_MEXICO" 
CREATE EXTENSION dblink;
\c "CENTAURO" 
CREATE EXTENSION dblink;
\c "NETSHOES" 
CREATE EXTENSION dblink;
\c "LIDSSPORTSGROUP" 
CREATE EXTENSION dblink;
\c "ATLETICO_MADRID" 
CREATE EXTENSION dblink;
\c "JET" 
CREATE EXTENSION dblink;
\c "AMY" 
CREATE EXTENSION dblink;
\c "TWO_FEET_UNDER" 
CREATE EXTENSION dblink;
\c "FITTEST_FREAKEST" 
CREATE EXTENSION dblink;
\c "NKJP_GFOOT" 
CREATE EXTENSION dblink;
\c "NKJP_STEP" 
CREATE EXTENSION dblink;
\c "NKJP_JUN" 
CREATE EXTENSION dblink;
\c "NKJP_MEGASPORTS" 
CREATE EXTENSION dblink;
\c "NKJP_STARJOINUS" 
CREATE EXTENSION dblink;
\c "NKGC_SHNDSPORTS" 
CREATE EXTENSION dblink;
\c "NKGC_CD_ADS_FTB" 
CREATE EXTENSION dblink;
\c "OFFICE_CONVERSE" 
CREATE EXTENSION dblink;
\c "CULTURE_KINGS" 
CREATE EXTENSION dblink;
\c "MORESPORT" 
CREATE EXTENSION dblink;
\c "MRTENNIS_MRRUNNING" 
CREATE EXTENSION dblink;
\c "ALIVE" 
CREATE EXTENSION dblink;
\c "GRUPO_JULIO" 
CREATE EXTENSION dblink;
\c "SOUL" 
CREATE EXTENSION dblink;
\c "BARRIO_WARRIOR" 
CREATE EXTENSION dblink;
\c "SRG" 
CREATE EXTENSION dblink;
\c "RPG" 
CREATE EXTENSION dblink;
\c "BD_SHENGSHI" 
CREATE EXTENSION dblink;
\c "TOP_SPORTS" 
CREATE EXTENSION dblink;
\c "NK_FL_EMEA_WEEKLY" 
CREATE EXTENSION dblink;
\c "NK_FL_EMEA_DAILY" 
CREATE EXTENSION dblink;
\c "NK_FL_EMEA_MONTHLY" 
CREATE EXTENSION dblink;
\c "NK_ACCENT_GROUP" 
CREATE EXTENSION dblink;
\c "INTERSPORT_GERMANY" 
CREATE EXTENSION dblink;
\c "BREUNINGER" 
CREATE EXTENSION dblink;
\c "TOTTENHAM" 
CREATE EXTENSION dblink;
\c "GAME7" 
CREATE EXTENSION dblink;
\c "LIVERPOOL_FC" 
CREATE EXTENSION dblink;
\c "NENCINI_SPORT" 
CREATE EXTENSION dblink;
\c "LA_REDOUTE" 
CREATE EXTENSION dblink;
\c "SARENZA" 
CREATE EXTENSION dblink;
\c "DE_BIJENKORF" 
CREATE EXTENSION dblink;
\c "FANATICS_US" 
CREATE EXTENSION dblink;
\c "CC_YUJIE" 
CREATE EXTENSION dblink;
\c "FAYA" 
CREATE EXTENSION dblink;
\c "FENGLEI" 
CREATE EXTENSION dblink;
\c "SCHUH" 
CREATE EXTENSION dblink;
\c "MACYS" 
CREATE EXTENSION dblink;
\c "GRUPO_AFEET" 
CREATE EXTENSION dblink;
\c "ICON" 
CREATE EXTENSION dblink;
\c "NSP" 
CREATE EXTENSION dblink;
\c "GRUPO_AXO" 
CREATE EXTENSION dblink;
\c "DPORTENIS" 
CREATE EXTENSION dblink;
\c "LUST" 
CREATE EXTENSION dblink;
\c "COPPEL" 
CREATE EXTENSION dblink;
\c "" 
CREATE EXTENSION dblink;
