\c "PNG_TC_PUB_MY_MERI_IV" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_MDSYNC" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_BALKANS" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_TURKEY" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_ISRAEL_1" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_ISRAEL_2" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_NE" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_NE_1" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_NE_2" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_ADP" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_AP" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_CAU" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_CCAR" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_CE" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_CE_1" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_EE" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_ID_CSA_IV" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_ID_PU_IV" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_ID_SLN_IV" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_JPN" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_MY_KTC_IV" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_MY_LHM_IV" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_SG_ALPHA_IV" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_SG_LINK_IV" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_TH_BKC_IV" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_TH_CNR_IV" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_TH_HDY_IV" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_TH_SMK_IV" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_TH_SRT_IV" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_ADP" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_AP" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_CAU" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_CCAR" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_CE" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_EE" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_GDMA" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_IMEA" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_PUB_ARGENTINA" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_PUB_CHILE" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_PUB_MASTERS" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_PUB_PERU" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_PUB_VENEZUELA" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_SUB_ARGENTINA" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_SUB_CHILE" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_SUB_PERU" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_SUB_VENEZUELA" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_BALKANS" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_TURKEY" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_ISRAEL" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_NE" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_ID" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_ID_1" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_MY" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_NZ" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_SG" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_TH" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_TH_1" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_TH_2" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_VN" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_VN_1" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_PH" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_PH_1" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_PH_2" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_ASEAN" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_MASTER" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_WA" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_SEA" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_SEA_1" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_NWA" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_NWA_1" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_WA" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_SEA" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_NWA" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_ASEAN_MY" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_ASEAN_ID" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_ASEAN_VN" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_ASEAN_TH" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_ASEAN_SG" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_ASEAN_NZ" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_ASEAN_PH" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_PUB_COLOMBIA" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_SUB_COLOMBIA" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_PUB_LADMAR" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_SUB_LADMAR" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_PUB_BRAZIL" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_SUB_BRAZIL" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_PUB_MEXICO" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_SUB_MEXICO" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_JPN_1" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_ASEAN_MYANMER" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_ASEAN_MYANMER" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_PUB_VENEZUELA_1" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_PUB_ARGENTINA_1" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_PUB_BRAZIL_1" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_PUB_MEXICO_1" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_PUB_LADMAR_1" 
CREATE EXTENSION dblink;
\c "PNG_TCLA_PUB_LADMAR_2" 
CREATE EXTENSION dblink;
\c "PNG_TC_PUB_ASEAN_VX" 
CREATE EXTENSION dblink;
\c "PNG_TC_SUB_ASEAN_VX" 
CREATE EXTENSION dblink;
\c "7255_COPIDROGUS_CO" 
CREATE EXTENSION dblink;
\c "7257_COLSUBSIDIO_CO" 
CREATE EXTENSION dblink;
\c "7256_OLIMPICA_CO" 
CREATE EXTENSION dblink;
\c "3947_COOPSAPPORTODOK_JP" 
CREATE EXTENSION dblink;
\c "3948_X5_RU" 
CREATE EXTENSION dblink;
\c "3946_SERRANO_GOMEZ_CO" 
CREATE EXTENSION dblink;
\c "7237_TAMIMI_AP" 
CREATE EXTENSION dblink;
\c "3933_CARREFOUR_AP" 
CREATE EXTENSION dblink;
\c "3930_BD_JP" 
CREATE EXTENSION dblink;
\c "3931_AMAZON_ABVP_CA" 
CREATE EXTENSION dblink;
\c "7232_JTA_LA" 
CREATE EXTENSION dblink;
\c "7234_SUPER_PHARM_LA" 
CREATE EXTENSION dblink;
\c "7244_LULU_SA" 
CREATE EXTENSION dblink;
\c "7246_GALAXIAS_GR" 
CREATE EXTENSION dblink;
\c "7247_CLICKS_ZA" 
CREATE EXTENSION dblink;
\c "7248_COPSERVIR_LTDA" 
CREATE EXTENSION dblink;
\c "7249_FARMATODO_COLOMBIA_SA" 
CREATE EXTENSION dblink;
\c "7250_CRUZ_VERDE_CO" 
CREATE EXTENSION dblink;
\c "3939_BIG_SAMS_BR" 
CREATE EXTENSION dblink;
\c "7238_CARREFOUR_PAKISTAN" 
CREATE EXTENSION dblink;
\c "7239_SPINNEYS_AE" 
CREATE EXTENSION dblink;
\c "7240_FARM_SA" 
CREATE EXTENSION dblink;
\c "7241_AJMAN_COOP_AE" 
CREATE EXTENSION dblink;
\c "7242_NESTO_AE" 
CREATE EXTENSION dblink;
\c "7243_AL_MEERA_QA" 
CREATE EXTENSION dblink;
\c "3958_ICA_SE" 
CREATE EXTENSION dblink;
\c "3957_ELKJOP_SE" 
CREATE EXTENSION dblink;
\c "3960_COOP_DK" 
CREATE EXTENSION dblink;
\c "3961_TOKMANNI_FI" 
CREATE EXTENSION dblink;
\c "3962_COOP_NO" 
CREATE EXTENSION dblink;
\c "3963_COOP_SE" 
CREATE EXTENSION dblink;
\c "3964_PRICELINE_AU" 
CREATE EXTENSION dblink;
\c "3932_NAHDI_AP" 
CREATE EXTENSION dblink;
\c "3965_ARTELI_MX" 
CREATE EXTENSION dblink;
\c "3966_MERCO_MX" 
CREATE EXTENSION dblink;
\c "3967_TREVINO_MX" 
CREATE EXTENSION dblink;
\c "7262_DISTRIBUCIONES_ROMA_CO" 
CREATE EXTENSION dblink;
\c "7263_EVE_CO" 
CREATE EXTENSION dblink;
\c "7264_UNIDROGAS_CO" 
CREATE EXTENSION dblink;
\c "3970_ASDA_COM_UK" 
CREATE EXTENSION dblink;
\c "7269_MALL_SLOVENIA" 
CREATE EXTENSION dblink;
\c "3968_KYORINDO_JP" 
CREATE EXTENSION dblink;
\c "3969_OKUWA_JP" 
CREATE EXTENSION dblink;
\c "7265_PANVEL_CATMAN_BR" 
CREATE EXTENSION dblink;
\c "7266_D1000_CATMAN_BR" 
CREATE EXTENSION dblink;
\c "PUB_TESCO" 
CREATE EXTENSION dblink;
\c "PUB_ASDA" 
CREATE EXTENSION dblink;
\c "PUB_SAINSBURY" 
CREATE EXTENSION dblink;
\c "PUB_WAITROSE" 
CREATE EXTENSION dblink;
\c "PUB_MEIJER" 
CREATE EXTENSION dblink;
\c "SUB_CUSTOMER_1" 
CREATE EXTENSION dblink;
\c "PUB_AMAZON" 
CREATE EXTENSION dblink;
\c "PUB_WALMART" 
CREATE EXTENSION dblink;
\c "PUB_DOLLARGENERAL" 
CREATE EXTENSION dblink;
\c "PUB_KROGER" 
CREATE EXTENSION dblink;
\c "PUB_TARGET" 
CREATE EXTENSION dblink;
\c "PUB_CVS" 
CREATE EXTENSION dblink;
\c "3926_DELHAIZE_RS" 
CREATE EXTENSION dblink;
\c "3921_MAGAZINE_LUIZA_BR" 
CREATE EXTENSION dblink;
\c "3922_MART_MINAS_BR" 
CREATE EXTENSION dblink;
\c "3924_AMAZON_BR" 
CREATE EXTENSION dblink;
\c "3925_DIA_A_DIA_BR" 
CREATE EXTENSION dblink;
\c "ALIDI_RU" 
CREATE EXTENSION dblink;
\c "7225_SPAR_STORES_ZA" 
CREATE EXTENSION dblink;
\c "7226_SPAR_NIELSEN_ZA" 
CREATE EXTENSION dblink;
\c "7227_PICK_N_PAY_NIELSEN_ZA" 
CREATE EXTENSION dblink;
\c "7228_DISCHEM_NIELSEN_ZA" 
CREATE EXTENSION dblink;
\c "7229_CLICKS_NIELSEN_ZA" 
CREATE EXTENSION dblink;
\c "7231_MALL_CZ" 
CREATE EXTENSION dblink;
\c "3927_WILDBERRIES_RU" 
CREATE EXTENSION dblink;
\c "3915_LECLERC_PT" 
CREATE EXTENSION dblink;
\c "3955_OLIVE_YOUNG_KR" 
CREATE EXTENSION dblink;
\c "7259_INTERNACIONAL_DE_DROGAS_CO" 
CREATE EXTENSION dblink;
\c "7260_ROHLIK_CZECH" 
CREATE EXTENSION dblink;
\c "7261_KIFLI_HUNGARY" 
CREATE EXTENSION dblink;
\c "3956_CONTINENTAL_ONLINE_PT" 
CREATE EXTENSION dblink;
\c "3951_CHEMIST_WAREHOUSE_AU" 
CREATE EXTENSION dblink;
\c "3950_SYNKA_GR" 
CREATE EXTENSION dblink;
\c "3949_ANEDIK_GR" 
CREATE EXTENSION dblink;
\c "7004_CARREFOUR_CATAMAN_BR" 
CREATE EXTENSION dblink;
\c "2712_MAKRO_CO" 
CREATE EXTENSION dblink;
\c "7271_DROGUERIAS_COMFANDI_CO" 
CREATE EXTENSION dblink;
\c "3971_SUPER_GUTIERREZ_MX" 
CREATE EXTENSION dblink;
\c "3972_OKEY_RU" 
CREATE EXTENSION dblink;
\c "3973_SBERMARKET_RU" 
CREATE EXTENSION dblink;
\c "3974_WILDBERRIES_RU_CATMAN" 
CREATE EXTENSION dblink;
\c "3977_METRO_PH" 
CREATE EXTENSION dblink;
\c "3978_SANDR_PH" 
CREATE EXTENSION dblink;
\c "3979_INDEPENDENT_WAREHOUSE_AU" 
CREATE EXTENSION dblink;
\c "3980_INDEPENDENT_WAREHOUSE_CATMAN_AU" 
CREATE EXTENSION dblink;
\c "3975_FINIPER_IT" 
CREATE EXTENSION dblink;
\c "3976_BENNET_IT" 
CREATE EXTENSION dblink;
\c "3987_WEGMANS_CATMAN_US" 
CREATE EXTENSION dblink;
\c "3986_CASINO_FR" 
CREATE EXTENSION dblink;
\c "3849_METRO_RU" 
CREATE EXTENSION dblink;
\c "3981_AUCHAN_OSA_FR" 
CREATE EXTENSION dblink;
\c "3982_INTERMARCHE_OSA_FR" 
CREATE EXTENSION dblink;
\c "7270_VENANCIO_CATMAN_BR" 
CREATE EXTENSION dblink;
\c "3983_TOPS_TH" 
CREATE EXTENSION dblink;
\c "3984_MAKRO_TH" 
CREATE EXTENSION dblink;
\c "3985_K_NET_JP" 
CREATE EXTENSION dblink;
\c "7236_DAWAA_AP" 
CREATE EXTENSION dblink;
\c "7251_TANDER_RU_CATMAN" 
CREATE EXTENSION dblink;
\c "3945_EPA_BR" 
CREATE EXTENSION dblink;
\c "7253_DROGUERIAS_CAFAM_CO" 
CREATE EXTENSION dblink;
\c "7254_LOCATEL_CO" 
CREATE EXTENSION dblink;
\c "3941_PHARMA_ES" 
CREATE EXTENSION dblink;
\c "3942_AMAZON_SA" 
CREATE EXTENSION dblink;
\c "3943_COLES_GATEWAY_AU" 
CREATE EXTENSION dblink;
\c "3944_URBAN_INDEPENDENT_CATMAN_US" 
CREATE EXTENSION dblink;
\c "3952_HYVEES_US" 
CREATE EXTENSION dblink;
\c "3953_ARKS_JP" 
CREATE EXTENSION dblink;
\c "3936_MRL_IN" 
CREATE EXTENSION dblink;
\c "3954_HOMBARGAIN_UK" 
CREATE EXTENSION dblink;
\c "7258_AXA_CO" 
CREATE EXTENSION dblink;
\c "7267_INDIANA_CATMAN_BR" 
CREATE EXTENSION dblink;
\c "7268_G_BARBOSA_CATMAN_BR" 
CREATE EXTENSION dblink;
\c "3923_VIA_VAREJO_BR" 
CREATE EXTENSION dblink;
\c "SUB_CUSTOMER_2" 
CREATE EXTENSION dblink;
\c "SUB_CUSTOMER_3" 
CREATE EXTENSION dblink;
\c "PUB_MORRISONS" 
CREATE EXTENSION dblink;
\c "7001_CONDOR_CATMAN_BR" 
CREATE EXTENSION dblink;
\c "7005_GPA_CATMAN_BR" 
CREATE EXTENSION dblink;
\c "7006_DROGARAIA_CATMAN_BR" 
CREATE EXTENSION dblink;
\c "7270_TAMBO_PE" 
CREATE EXTENSION dblink;
\c "3959_SALLING_DK" 
CREATE EXTENSION dblink;
\c "PNGLT_PUB_TARGET" 
CREATE EXTENSION dblink;
\c "PNGLT_PUB_SAMS" 
CREATE EXTENSION dblink;
\c "PNGLT_US" 
CREATE EXTENSION dblink;
\c "3887_DM_RO" 
CREATE EXTENSION dblink;
\c "3859_YAKUOHDO" 
CREATE EXTENSION dblink;
\c "3860_PROFI" 
CREATE EXTENSION dblink;
\c "7067_CLICKS" 
CREATE EXTENSION dblink;
\c "7068_SHOPRITE" 
CREATE EXTENSION dblink;
\c "7069_DISCHEM" 
CREATE EXTENSION dblink;
\c "7071_GAME" 
CREATE EXTENSION dblink;
\c "7072_SPAR" 
CREATE EXTENSION dblink;
\c "7073_TESCO" 
CREATE EXTENSION dblink;
\c "7074_BIGC" 
CREATE EXTENSION dblink;
\c "3862_CARREFOUR" 
CREATE EXTENSION dblink;
\c "7076_TESCO" 
CREATE EXTENSION dblink;
\c "7077_GIANT" 
CREATE EXTENSION dblink;
\c "7078_WATSON" 
CREATE EXTENSION dblink;
\c "7079_GIANT" 
CREATE EXTENSION dblink;
\c "7080_COLD_STORAGE" 
CREATE EXTENSION dblink;
\c "7081_WATSON" 
CREATE EXTENSION dblink;
\c "7082_GUARDIAN" 
CREATE EXTENSION dblink;
\c "7083_ASSAI" 
CREATE EXTENSION dblink;
\c "7084_ARA" 
CREATE EXTENSION dblink;
\c "3861_SOK" 
CREATE EXTENSION dblink;
\c "3863_TENDA" 
CREATE EXTENSION dblink;
\c "3864_DIMED" 
CREATE EXTENSION dblink;
\c "3865_VENANCIO" 
CREATE EXTENSION dblink;
\c "3866_ROLDAO" 
CREATE EXTENSION dblink;
\c "7085_COOP" 
CREATE EXTENSION dblink;
\c "7086_VINMART" 
CREATE EXTENSION dblink;
\c "PNG_CHINA" 
CREATE EXTENSION dblink;
\c "3854_DAGROF" 
CREATE EXTENSION dblink;
\c "7075_AEON_BIG" 
CREATE EXTENSION dblink;
\c "" 
CREATE EXTENSION dblink;
