\c "RB_SRI_LANKA_SFA_NEWSPAGE" 
CREATE EXTENSION dblink;
\c "RB_AFRICA_NIELSEN_POS_HC" 
CREATE EXTENSION dblink;
\c "RBPULSE_AFRICA" 
CREATE EXTENSION dblink;
\c "RB_INDONESIA_SMFA_NEWSPAGE" 
CREATE EXTENSION dblink;
\c "RB_BANGLADESH_SFA_NEWSPAGE" 
CREATE EXTENSION dblink;
\c "RB_EGYPT_MFA_NEWSPAGE" 
CREATE EXTENSION dblink;
\c "RB_MALAYSIA_MFA_NP" 
CREATE EXTENSION dblink;
\c "RB_MALAYSIA_SFA_NP" 
CREATE EXTENSION dblink;
\c "RB_SINGAPORE_MFA_NP" 
CREATE EXTENSION dblink;
\c "RB_MALAYSIA_ZULING_IMS" 
CREATE EXTENSION dblink;
\c "RBPULSE_MYS" 
CREATE EXTENSION dblink;
\c "RBPULSE_SGP" 
CREATE EXTENSION dblink;
\c "REACH" 
CREATE EXTENSION dblink;
\c "RB_NEWSPAGE" 
CREATE EXTENSION dblink;
\c "RB_JAPAN_POS" 
CREATE EXTENSION dblink;
\c "RB_NOA_RBONE" 
CREATE EXTENSION dblink;
\c "RB_PHL_RBONE" 
CREATE EXTENSION dblink;
\c "RB_SAF_RBONE" 
CREATE EXTENSION dblink;
\c "RB_ARG_RBONE" 
CREATE EXTENSION dblink;
\c "RB_MOROCCO_MFA_NEWSPAGE" 
CREATE EXTENSION dblink;
\c "RB_NIGERIA_SFA_NEWSPAGE" 
CREATE EXTENSION dblink;
\c "RB_PHILIPPINES_SFA_NEWSPAGE" 
CREATE EXTENSION dblink;
\c "RB_THAILAND_SFA_NEWSPAGE" 
CREATE EXTENSION dblink;
\c "RB_IDN_RBONE" 
CREATE EXTENSION dblink;
\c "RB_BGD_RBONE" 
CREATE EXTENSION dblink;
\c "RB_NP_EGY_RBONE" 
CREATE EXTENSION dblink;
\c "RB_HKG_RBONE" 
CREATE EXTENSION dblink;
\c "RB_NP_ARA_RBONE" 
CREATE EXTENSION dblink;
\c "RB_LKA_RBONE" 
CREATE EXTENSION dblink;
\c "RB_PHILIPPINES_IMS" 
CREATE EXTENSION dblink;
\c "RB_TWN_SMFA_NEWSPAGE" 
CREATE EXTENSION dblink;
\c "RB_NP_TAIWAN_RBONE" 
CREATE EXTENSION dblink;
\c "RB_THAILAND_IMS" 
CREATE EXTENSION dblink;
\c "RB_MENA_POS" 
CREATE EXTENSION dblink;
\c "RB_SOUTH_AFRICA_POS" 
CREATE EXTENSION dblink;
\c "RB_THAILAND_POS" 
CREATE EXTENSION dblink;
\c "RB_JAPAN_IMS" 
CREATE EXTENSION dblink;
\c "RB_NOA_IMS" 
CREATE EXTENSION dblink;
\c "RB_KENYA_IMS" 
CREATE EXTENSION dblink;
\c "RB_JAPAN_RBONE" 
CREATE EXTENSION dblink;
\c "RB_KENYA_RBONE" 
CREATE EXTENSION dblink;
\c "RB_MENA_RBONE" 
CREATE EXTENSION dblink;
\c "RB_NIGERIA_RBONE" 
CREATE EXTENSION dblink;
\c "RB_MEX_NEWSPAGE_HC" 
CREATE EXTENSION dblink;
\c "RBPULSE_PHL" 
CREATE EXTENSION dblink;
\c "RB_HONG_KONG_SMFA_NEWSPAGE" 
CREATE EXTENSION dblink;
\c "RB_PHL_IMS" 
CREATE EXTENSION dblink;
\c "RBONE" 
CREATE EXTENSION dblink;
\c "ZAMBIA_NEWSPAGE" 
CREATE EXTENSION dblink;
\c "RB_SEA_EPOS" 
CREATE EXTENSION dblink;
\c "RB_SEA_RBONE" 
CREATE EXTENSION dblink;
\c "RB_MEX_RBPULSE_HC" 
CREATE EXTENSION dblink;
\c "RB_THA_RBONE" 
CREATE EXTENSION dblink;
\c "RB_ARG_IMS_NCC" 
CREATE EXTENSION dblink;
\c "RB_SINGAPORE_IMS" 
CREATE EXTENSION dblink;
\c "RB_MENA_IMS" 
CREATE EXTENSION dblink;
\c "RB_HEALTH" 
CREATE EXTENSION dblink;
\c "RB_GRE_NEWSPAGE_HC" 
CREATE EXTENSION dblink;
\c "RB_ARG_NEWSPAGE_HC" 
CREATE EXTENSION dblink;
\c "RB_GREECE_RBONE_HC" 
CREATE EXTENSION dblink;
\c "RB_ARG_RBONE_HC" 
CREATE EXTENSION dblink;
\c "mcm_psm_teda_testpub1" 
CREATE EXTENSION dblink;
\c "AL_ETS_DEHABA" 
CREATE EXTENSION dblink;
\c "SELFRIDGES" 
CREATE EXTENSION dblink;
\c "LITTLEWOODS" 
CREATE EXTENSION dblink;
\c "SILESIA_JEANS" 
CREATE EXTENSION dblink;
\c "KLG_HASSANI_UAE" 
CREATE EXTENSION dblink;
\c "DUZEY" 
CREATE EXTENSION dblink;
\c "KELLOGG" 
CREATE EXTENSION dblink;
\c "KLG_JORDAN" 
CREATE EXTENSION dblink;
\c "KHC_PROMERCO_CL" 
CREATE EXTENSION dblink;
\c "KHC_TAGAROPULOS" 
CREATE EXTENSION dblink;
\c "ET_ADDISU" 
CREATE EXTENSION dblink;
\c "MZ_HEINEKEN" 
CREATE EXTENSION dblink;
\c "SL_BAYCO" 
CREATE EXTENSION dblink;
\c "SL_PATRILIA" 
CREATE EXTENSION dblink;
\c "SL_MARY_SONS" 
CREATE EXTENSION dblink;
\c "RW_COBETRAB" 
CREATE EXTENSION dblink;
\c "RW_CODICO" 
CREATE EXTENSION dblink;
\c "RW_SODICOBA" 
CREATE EXTENSION dblink;
\c "RW_HAKANI" 
CREATE EXTENSION dblink;
\c "RW_SOCOH" 
CREATE EXTENSION dblink;
\c "ET_ALEMAYEHU" 
CREATE EXTENSION dblink;
\c "ET_BELACHEW" 
CREATE EXTENSION dblink;
\c "ET_BELAY" 
CREATE EXTENSION dblink;
\c "ET_BELETETES" 
CREATE EXTENSION dblink;
\c "ET_FIKADU" 
CREATE EXTENSION dblink;
\c "ET_TESFAYE" 
CREATE EXTENSION dblink;
\c "ET_TESSEMA" 
CREATE EXTENSION dblink;
\c "ET_TSEDEKE" 
CREATE EXTENSION dblink;
\c "ET_WELDAY" 
CREATE EXTENSION dblink;
\c "CI_HEINEKEN" 
CREATE EXTENSION dblink;
\c "RW_BEDITRA" 
CREATE EXTENSION dblink;
\c "RW_BUDEYI" 
CREATE EXTENSION dblink;
\c "RW_COLIBA" 
CREATE EXTENSION dblink;
\c "RW_CON_FAMILY" 
CREATE EXTENSION dblink;
\c "RW_DISDPROCO" 
CREATE EXTENSION dblink;
\c "RW_DITRAC_SOLUTION" 
CREATE EXTENSION dblink;
\c "RW_DVB" 
CREATE EXTENSION dblink;
\c "RW_FAPROCO" 
CREATE EXTENSION dblink;
\c "RW_FURAHA" 
CREATE EXTENSION dblink;
\c "RW_GAHIRE" 
CREATE EXTENSION dblink;
\c "RW_GPTC" 
CREATE EXTENSION dblink;
\c "RW_HARELIMANA" 
CREATE EXTENSION dblink;
\c "RW_HEINEKEN" 
CREATE EXTENSION dblink;
\c "RW_JACE_FAMILY" 
CREATE EXTENSION dblink;
\c "RW_KAFACO" 
CREATE EXTENSION dblink;
\c "RW_KAMONSONS" 
CREATE EXTENSION dblink;
\c "RW_KARURANGA" 
CREATE EXTENSION dblink;
\c "RW_KURA_DISTRIBUTOR" 
CREATE EXTENSION dblink;
\c "RW_MAFAM" 
CREATE EXTENSION dblink;
\c "RW_MUDISA" 
CREATE EXTENSION dblink;
\c "RW_MUKABIRASA" 
CREATE EXTENSION dblink;
\c "RW_NDAHIRIWE" 
CREATE EXTENSION dblink;
\c "RW_NTAGOZERA" 
CREATE EXTENSION dblink;
\c "RW_NZAFAMICO" 
CREATE EXTENSION dblink;
\c "RW_RUNMETA_FAMILY" 
CREATE EXTENSION dblink;
\c "RW_RWABUKAMBA" 
CREATE EXTENSION dblink;
\c "RW_SADICO" 
CREATE EXTENSION dblink;
\c "RW_SAMUEL_NDUWUMWE" 
CREATE EXTENSION dblink;
\c "RW_SCODI" 
CREATE EXTENSION dblink;
\c "RW_SODITRACO" 
CREATE EXTENSION dblink;
\c "RW_SOFATHEBE" 
CREATE EXTENSION dblink;
\c "RW_SOTKAMU" 
CREATE EXTENSION dblink;
\c "RW_SOTRACOGE" 
CREATE EXTENSION dblink;
\c "RW_SOVEPROA" 
CREATE EXTENSION dblink;
\c "RW_SRDS" 
CREATE EXTENSION dblink;
\c "RW_SUGIRA" 
CREATE EXTENSION dblink;
\c "RW_VINO_GAUDIUM" 
CREATE EXTENSION dblink;
\c "TU_BEN_ABDELLATIF" 
CREATE EXTENSION dblink;
\c "TU_COMPTOIR" 
CREATE EXTENSION dblink;
\c "TU_HEINEKEN" 
CREATE EXTENSION dblink;
\c "TU_MOULAHI_FAICEL" 
CREATE EXTENSION dblink;
\c "TU_STE_BEJAOUI" 
CREATE EXTENSION dblink;
\c "TU_STE_FAWZ" 
CREATE EXTENSION dblink;
\c "ALIBINALI" 
CREATE EXTENSION dblink;
\c "OMANREFRESHMENT" 
CREATE EXTENSION dblink;
\c "UNITEDBEVERAGE" 
CREATE EXTENSION dblink;
\c "AHMADIINDUSTRIES" 
CREATE EXTENSION dblink;
\c "SUNTORYPEPSICO" 
CREATE EXTENSION dblink;
\c "JORDANICEAERATED" 
CREATE EXTENSION dblink;
\c "PERMANIS" 
CREATE EXTENSION dblink;
\c "DUBAIREFRESHMENT" 
CREATE EXTENSION dblink;
\c "ABUDHABIREFRESHMENT" 
CREATE EXTENSION dblink;
\c "PERMANIS_GUAM" 
CREATE EXTENSION dblink;
\c "PERMANIS_SGP" 
CREATE EXTENSION dblink;
\c "PEPSILIPTON" 
CREATE EXTENSION dblink;
\c "PEPSICO_INDIA" 
CREATE EXTENSION dblink;
\c "PEPSICOLA_THAI" 
CREATE EXTENSION dblink;
\c "SOCIETEMODERNE" 
CREATE EXTENSION dblink;
\c "LOTTECHILSUNG" 
CREATE EXTENSION dblink;
\c "ABDELHADIABDULLAH" 
CREATE EXTENSION dblink;
\c "SAUDIINDUSTRIAL" 
CREATE EXTENSION dblink;
\c "ALJOMAIHBOTTLING" 
CREATE EXTENSION dblink;
\c "ALJOMAIHBOTTLINGPLANTS" 
CREATE EXTENSION dblink;
\c "CUETARA_MX" 
CREATE EXTENSION dblink;
\c "CYS_PR" 
CREATE EXTENSION dblink;
\c "KHC_FACEY_COMMODITY" 
CREATE EXTENSION dblink;
\c "KHC_MASSY_US" 
CREATE EXTENSION dblink;
\c "PPC_PR" 
CREATE EXTENSION dblink;
\c "KLG_BAHRAIN" 
CREATE EXTENSION dblink;
\c "KLG_QATAR" 
CREATE EXTENSION dblink;
\c "ET_YARED" 
CREATE EXTENSION dblink;
\c "ET_ABATHUN" 
CREATE EXTENSION dblink;
\c "ET_BABESHA" 
CREATE EXTENSION dblink;
\c "ET_YILMA" 
CREATE EXTENSION dblink;
\c "ET_ABU" 
CREATE EXTENSION dblink;
\c "ET_JINKA" 
CREATE EXTENSION dblink;
\c "ET_KETEMA" 
CREATE EXTENSION dblink;
\c "ET_TSEGE" 
CREATE EXTENSION dblink;
\c "ET_HAGAREMARIAM" 
CREATE EXTENSION dblink;
\c "ET_TEKLEMARIAM" 
CREATE EXTENSION dblink;
\c "ET_MENEGESHA" 
CREATE EXTENSION dblink;
\c "ET_KAHSAYWOLDESILASSIE" 
CREATE EXTENSION dblink;
\c "ET_GOSHU" 
CREATE EXTENSION dblink;
\c "MZ_MUTHOMBOTE" 
CREATE EXTENSION dblink;
\c "SL_MEMS" 
CREATE EXTENSION dblink;
\c "SL_KASASA" 
CREATE EXTENSION dblink;
\c "SL_HEINEKEN" 
CREATE EXTENSION dblink;
\c "CI_MERKATO_SARL" 
CREATE EXTENSION dblink;
\c "AL_HOUAMDI_MALEK" 
CREATE EXTENSION dblink;
\c "CI_COQUILLE" 
CREATE EXTENSION dblink;
\c "CI_COMPAGNIE" 
CREATE EXTENSION dblink;
\c "CI_KONAN" 
CREATE EXTENSION dblink;
\c "CI_AKN" 
CREATE EXTENSION dblink;
\c "CI_ETS" 
CREATE EXTENSION dblink;
\c "CI_SENIKAB" 
CREATE EXTENSION dblink;
\c "CI_IVOIRIENNE" 
CREATE EXTENSION dblink;
\c "TU_MOULAHI_GABES" 
CREATE EXTENSION dblink;
\c "TU_STE_ALIMENTAIRE" 
CREATE EXTENSION dblink;
\c "NIELSEN_US" 
CREATE EXTENSION dblink;
\c "KRAFT_HEINZ" 
CREATE EXTENSION dblink;
\c "TU_STE_HABIB" 
CREATE EXTENSION dblink;
\c "MZ_ST_DIST" 
CREATE EXTENSION dblink;
\c "MZ_BDR_DISTRIBUICAO" 
CREATE EXTENSION dblink;
\c "RW_FREEWAY" 
CREATE EXTENSION dblink;
\c "RW_KEYAL" 
CREATE EXTENSION dblink;
\c "RW_RUDISI" 
CREATE EXTENSION dblink;
\c "RW_RUPIYA" 
CREATE EXTENSION dblink;
\c "RW_BUDCO" 
CREATE EXTENSION dblink;
\c "TEMCMSTD_CONFIG" 
CREATE EXTENSION dblink;
\c "TESTTENANT_SUB" 
CREATE EXTENSION dblink;
\c "RW_FAMILYSOLUTION" 
CREATE EXTENSION dblink;
\c "MCM_MIGRATION_1" 
CREATE EXTENSION dblink;
\c "BU_HEINEKEN" 
CREATE EXTENSION dblink;
\c "RW_DDB" 
CREATE EXTENSION dblink;
\c "UNILIVER_AUSTRALIA" 
CREATE EXTENSION dblink;
\c "KHC_LEOPOLDO_GROSS" 
CREATE EXTENSION dblink;
\c "BU_BAZOMPORA" 
CREATE EXTENSION dblink;
\c "KHC_COMPRA_LTD" 
CREATE EXTENSION dblink;
\c "ET_GEDA" 
CREATE EXTENSION dblink;
\c "ET_GETNET" 
CREATE EXTENSION dblink;
\c "ET_HIWOT" 
CREATE EXTENSION dblink;
\c "ET_KAHSAY" 
CREATE EXTENSION dblink;
\c "ET_KASSA" 
CREATE EXTENSION dblink;
\c "ET_KIBKO" 
CREATE EXTENSION dblink;
\c "ET_MEKONNEN" 
CREATE EXTENSION dblink;
\c "ET_MELAKU" 
CREATE EXTENSION dblink;
\c "ET_MENGISTU" 
CREATE EXTENSION dblink;
\c "ET_MULATU" 
CREATE EXTENSION dblink;
\c "ET_SELEMON" 
CREATE EXTENSION dblink;
\c "ET_WERKU" 
CREATE EXTENSION dblink;
\c "ET_WESSEN" 
CREATE EXTENSION dblink;
\c "ET_WORKNEH" 
CREATE EXTENSION dblink;
\c "ET_WOSENE" 
CREATE EXTENSION dblink;
\c "ET_YESHITILA" 
CREATE EXTENSION dblink;
\c "ET_YOSEPH" 
CREATE EXTENSION dblink;
\c "ET_ZELALEM" 
CREATE EXTENSION dblink;
\c "HEINEKEN" 
CREATE EXTENSION dblink;
\c "AL_AL_EURL_TENIRI" 
CREATE EXTENSION dblink;
\c "AL_HEINEKEN" 
CREATE EXTENSION dblink;
\c "AL_MANSEUR_IDIR" 
CREATE EXTENSION dblink;
\c "AL_SARL_AMERIGE" 
CREATE EXTENSION dblink;
\c "AL_SARL_CORAIL" 
CREATE EXTENSION dblink;
\c "RW_ABASANGIRA" 
CREATE EXTENSION dblink;
\c "VARUNBEVERAGES" 
CREATE EXTENSION dblink;
\c "PEPSI_COLA_EGYPT" 
CREATE EXTENSION dblink;
\c "KLG_SAUDI_ARABIA" 
CREATE EXTENSION dblink;
\c "KLG_CYPRUS" 
CREATE EXTENSION dblink;
\c "KLG_ISRAEL" 
CREATE EXTENSION dblink;
\c "KLG_TRANSMED_LEBANON" 
CREATE EXTENSION dblink;
\c "KLG_OMAN" 
CREATE EXTENSION dblink;
\c "SINO_KELL" 
CREATE EXTENSION dblink;
\c "SINO_PRNG" 
CREATE EXTENSION dblink;
\c "KLG_WBG" 
CREATE EXTENSION dblink;
\c "KLG_GREECE" 
CREATE EXTENSION dblink;
\c "KLG_MALTA" 
CREATE EXTENSION dblink;
\c "KLG_EAM_LEBANON" 
CREATE EXTENSION dblink;
\c "KLG_KUWAIT" 
CREATE EXTENSION dblink;
\c "KLG_TRANSMED_UAE" 
CREATE EXTENSION dblink;
\c "ET_TERECHE" 
CREATE EXTENSION dblink;
\c "MZ_CICOTI" 
CREATE EXTENSION dblink;
\c "SL_SUGARLOAF" 
CREATE EXTENSION dblink;
\c "SL_MARIESNELL" 
CREATE EXTENSION dblink;
\c "SL_HAWAFODAY" 
CREATE EXTENSION dblink;
\c "SL_STAR" 
CREATE EXTENSION dblink;
\c "RW_ALDITRASSO" 
CREATE EXTENSION dblink;
\c "PHIL_PRG" 
CREATE EXTENSION dblink;
\c "PHIL_RTEC" 
CREATE EXTENSION dblink;
\c "AL_EURL_BOISSONS" 
CREATE EXTENSION dblink;
\c "NEXT_RETAIL" 
CREATE EXTENSION dblink;
\c "PEPSICOLA_PH" 
CREATE EXTENSION dblink;
\c "KLG_EGYPT" 
CREATE EXTENSION dblink;
\c "AL_AIT_SAID" 
CREATE EXTENSION dblink;
\c "AL_HAMIA_BELAID" 
CREATE EXTENSION dblink;
\c "RW_DUHOZANYE" 
CREATE EXTENSION dblink;
\c "MZ_TROPIGALIA" 
CREATE EXTENSION dblink;
\c "" 
CREATE EXTENSION dblink;
