\c "RW_KIMONYI" 
CREATE EXTENSION dblink;
\c "KROGER" 
CREATE EXTENSION dblink;
\c "PETCO" 
CREATE EXTENSION dblink;
\c "INTL_PUB_OLR" 
CREATE EXTENSION dblink;
\c "RW_KIVUYE" 
CREATE EXTENSION dblink;
\c "RW_KWA_PAUL" 
CREATE EXTENSION dblink;
\c "RW_PETER" 
CREATE EXTENSION dblink;
\c "RW_RUSUMO" 
CREATE EXTENSION dblink;
\c "RW_RUTURUSU" 
CREATE EXTENSION dblink;
\c "INTL_PUBLISHER_11" 
CREATE EXTENSION dblink;
\c "RW_YOAUNDE" 
CREATE EXTENSION dblink;
\c "RW_PALEUM_LTD" 
CREATE EXTENSION dblink;
\c "RW_KABARE" 
CREATE EXTENSION dblink;
\c "RW_RUGENDE_1" 
CREATE EXTENSION dblink;
\c "RW_BIREMBO" 
CREATE EXTENSION dblink;
\c "RW_FAUSTIN" 
CREATE EXTENSION dblink;
\c "RW_KAJAGARI" 
CREATE EXTENSION dblink;
\c "RW_NDABIKUNZE" 
CREATE EXTENSION dblink;
\c "RW_NDAYISENGA" 
CREATE EXTENSION dblink;
\c "RW_BEATRICE" 
CREATE EXTENSION dblink;
\c "RW_EMMANUEL" 
CREATE EXTENSION dblink;
\c "RW_SOUZANE" 
CREATE EXTENSION dblink;
\c "RW_KUMUDERI" 
CREATE EXTENSION dblink;
\c "RW_PRUDENCE" 
CREATE EXTENSION dblink;
\c "RW_KAJAGARI_II" 
CREATE EXTENSION dblink;
\c "RW_SHYAKA" 
CREATE EXTENSION dblink;
\c "URC" 
CREATE EXTENSION dblink;
\c "URC_SAP_ECC" 
CREATE EXTENSION dblink;
\c "URC_SFA" 
CREATE EXTENSION dblink;
\c "URC_SAP_BW" 
CREATE EXTENSION dblink;
\c "SODICOM" 
CREATE EXTENSION dblink;
\c "DIAGEO_ESEA" 
CREATE EXTENSION dblink;
\c "LOREAL_KCL" 
CREATE EXTENSION dblink;
\c "TU_SOPAB" 
CREATE EXTENSION dblink;
\c "TU_HILEL" 
CREATE EXTENSION dblink;
\c "NAVABI_GMBH" 
CREATE EXTENSION dblink;
\c "TU_SOCONO" 
CREATE EXTENSION dblink;
\c "NESTLE_PUB_ALBERTSON" 
CREATE EXTENSION dblink;
\c "NESTLE_PUB_DELHAIZE" 
CREATE EXTENSION dblink;
\c "NESTLE_PUB_AHOLD" 
CREATE EXTENSION dblink;
\c "NESTLE_PUB_GIANT_EAGLE" 
CREATE EXTENSION dblink;
\c "DIAGEO_TH" 
CREATE EXTENSION dblink;
\c "ARCADIA_GROUP" 
CREATE EXTENSION dblink;
\c "MZ_SYNAVIX" 
CREATE EXTENSION dblink;
\c "SNIPES" 
CREATE EXTENSION dblink;
\c "FAMA" 
CREATE EXTENSION dblink;
\c "TRADELINE" 
CREATE EXTENSION dblink;
\c "FENWICK" 
CREATE EXTENSION dblink;
\c "DANTE_INTERNATIONAL" 
CREATE EXTENSION dblink;
\c "GAME_SEVEN" 
CREATE EXTENSION dblink;
\c "HNK_GDF_MACLNTYRE" 
CREATE EXTENSION dblink;
\c "HNK_GDF_PENTRADE" 
CREATE EXTENSION dblink;
\c "HNK_GDF_TOPLINE" 
CREATE EXTENSION dblink;
\c "HNK_GDF_MAIN" 
CREATE EXTENSION dblink;
\c "CARLSBERG_UC3" 
CREATE EXTENSION dblink;
\c "CARLSBERG_UC4" 
CREATE EXTENSION dblink;
\c "STRATEGIO_PACIFICO" 
CREATE EXTENSION dblink;
\c "INSTORE_VIEW_CHILE" 
CREATE EXTENSION dblink;
\c "MDLZ_LATAM" 
CREATE EXTENSION dblink;
\c "DIAGEO_VIETNAM" 
CREATE EXTENSION dblink;
\c "TU_SAHEL" 
CREATE EXTENSION dblink;
\c "TU_MIDANI" 
CREATE EXTENSION dblink;
\c "MDLZ_VTNM_SUBSCRIBER" 
CREATE EXTENSION dblink;
\c "MDCOE_REPORT_RE_PUBLISHER2" 
CREATE EXTENSION dblink;
\c "MDCOE_REPORT_SUBSCRIBER" 
CREATE EXTENSION dblink;
\c "MDLZ_GREECE_SUBSCRIBER" 
CREATE EXTENSION dblink;
\c "MDLZ_UKRAINE_PUBLISHER" 
CREATE EXTENSION dblink;
\c "MDLZ_CSZK_PUBLISHER" 
CREATE EXTENSION dblink;
\c "MDLZ_CSZK_SUBSCRIBER" 
CREATE EXTENSION dblink;
\c "MDLZ_TURKEY_PUBLISHER" 
CREATE EXTENSION dblink;
\c "MDLZ_TURKEY_SUBSCRIBER" 
CREATE EXTENSION dblink;
\c "MDLZ_SLOVAKIA_PUBLISHER" 
CREATE EXTENSION dblink;
\c "MDLZ_SLOVAKIA_SUBSCRIBER" 
CREATE EXTENSION dblink;
\c "MDLZ_GREECE_PUBLISHER" 
CREATE EXTENSION dblink;
\c "TU_SDD" 
CREATE EXTENSION dblink;
\c "MDLZ_UKRAINE_SUBSCRIBER" 
CREATE EXTENSION dblink;
\c "GDF_COFRAPEX" 
CREATE EXTENSION dblink;
\c "GDF_CONNAUGHTON" 
CREATE EXTENSION dblink;
\c "GDF_TABAK" 
CREATE EXTENSION dblink;
\c "GDF_OVERSEAS" 
CREATE EXTENSION dblink;
\c "GDF_ACEWIDE" 
CREATE EXTENSION dblink;
\c "GDF_AGNA" 
CREATE EXTENSION dblink;
\c "GDF_BOREAS" 
CREATE EXTENSION dblink;
\c "GDF_MARINE" 
CREATE EXTENSION dblink;
\c "GDF_XIAMEN" 
CREATE EXTENSION dblink;
\c "TU_KHALED_BOUDEGGA" 
CREATE EXTENSION dblink;
\c "TU_MONDIALE" 
CREATE EXTENSION dblink;
\c "TU_3F" 
CREATE EXTENSION dblink;
\c "LIVERPOOL_LEVI" 
CREATE EXTENSION dblink;
\c "SEARS_LEVI" 
CREATE EXTENSION dblink;
\c "DIAGEO_AFRICA" 
CREATE EXTENSION dblink;
\c "RW_BASEHNK" 
CREATE EXTENSION dblink;
\c "DIAGEO_AFRICA_CENTRAL" 
CREATE EXTENSION dblink;
\c "IVC_BASEHNK" 
CREATE EXTENSION dblink;
\c "DIAGEO_AFRICA_WEST" 
CREATE EXTENSION dblink;
\c "DIAGEO_AFRICA_ANGOLA" 
CREATE EXTENSION dblink;
\c "DIAGEO_AFRICA_SAEM" 
CREATE EXTENSION dblink;
\c "BASE_HEINEKEN" 
CREATE EXTENSION dblink;
\c "SL_SIERRA_SIPS" 
CREATE EXTENSION dblink;
\c "SL_OBTE" 
CREATE EXTENSION dblink;
\c "RW_CHEZKAYIBANDA" 
CREATE EXTENSION dblink;
\c "RW_BUYOGA" 
CREATE EXTENSION dblink;
\c "RW_KISARO" 
CREATE EXTENSION dblink;
\c "RW_GIKOMERO" 
CREATE EXTENSION dblink;
\c "RW_RUTUNGA" 
CREATE EXTENSION dblink;
\c "RW_CORNERBAR" 
CREATE EXTENSION dblink;
\c "RW_NDEZE250789640773" 
CREATE EXTENSION dblink;
\c "RW_CYUMBATISP" 
CREATE EXTENSION dblink;
\c "RW_OLIVESPSP" 
CREATE EXTENSION dblink;
\c "MDLZ_MY_PUB" 
CREATE EXTENSION dblink;
\c "MDLZ_MY_SUB" 
CREATE EXTENSION dblink;
\c "MDLZ_IDN_PUB" 
CREATE EXTENSION dblink;
\c "MDLZ_RSA_PUBLISHER" 
CREATE EXTENSION dblink;
\c "MDLZ_RSA_SUBSCRIBER" 
CREATE EXTENSION dblink;
\c "MDLZ_PH_DMS" 
CREATE EXTENSION dblink;
\c "MDLZ_IDN_SUB" 
CREATE EXTENSION dblink;
\c "DIAGEO_INDONESIA" 
CREATE EXTENSION dblink;
\c "OUTFITTERY_GMBH" 
CREATE EXTENSION dblink;
\c "KHAKI_CRAZY" 
CREATE EXTENSION dblink;
\c "NAKDCOM" 
CREATE EXTENSION dblink;
\c "MACHOUSE" 
CREATE EXTENSION dblink;
\c "RIGHTON" 
CREATE EXTENSION dblink;
\c "DSEDI" 
CREATE EXTENSION dblink;
\c "JEANSMATE" 
CREATE EXTENSION dblink;
\c "ISETAN" 
CREATE EXTENSION dblink;
\c "MYERS" 
CREATE EXTENSION dblink;
\c "TEKSAPOISS_OU" 
CREATE EXTENSION dblink;
\c "CB_ASIA_FIT" 
CREATE EXTENSION dblink;
\c "CB_ASIA_PFTY" 
CREATE EXTENSION dblink;
\c "CB_ASIA_SVNLSN" 
CREATE EXTENSION dblink;
\c "HNK_GDF_TCS" 
CREATE EXTENSION dblink;
\c "HNK_GDF_MILLET" 
CREATE EXTENSION dblink;
\c "HNK_GDF_BARCELONA" 
CREATE EXTENSION dblink;
\c "HNK_GDF_PEGASUS" 
CREATE EXTENSION dblink;
\c "HNK_GDF_MEGROUP" 
CREATE EXTENSION dblink;
\c "HNK_GDF_CHARLSGRECH" 
CREATE EXTENSION dblink;
\c "HNK_GDF_MEBALTICS" 
CREATE EXTENSION dblink;
\c "HNK_GDF_HEINEMANN" 
CREATE EXTENSION dblink;
\c "HNK_GDF_STENA" 
CREATE EXTENSION dblink;
\c "STRATEGIO_CHILE" 
CREATE EXTENSION dblink;
\c "SORT_CAM" 
CREATE EXTENSION dblink;
\c "MDLZ_OSA_MY_PUB" 
CREATE EXTENSION dblink;
\c "MDLZ_OSA_MY_SUB" 
CREATE EXTENSION dblink;
\c "CI_DIST600001" 
CREATE EXTENSION dblink;
\c "CI_DIST600002" 
CREATE EXTENSION dblink;
\c "SL_SINANQUA" 
CREATE EXTENSION dblink;
\c "RW_POINTDEMARAGESP" 
CREATE EXTENSION dblink;
\c "RW_NYABIMATA" 
CREATE EXTENSION dblink;
\c "RW_BIGOGWE" 
CREATE EXTENSION dblink;
\c "RW_HANGARI" 
CREATE EXTENSION dblink;
\c "RW_GISANGANI" 
CREATE EXTENSION dblink;
\c "RW_RAMIRO" 
CREATE EXTENSION dblink;
\c "RW_SEBACURUZI" 
CREATE EXTENSION dblink;
\c "RW_IDRISSA" 
CREATE EXTENSION dblink;
\c "RW_CAFFE" 
CREATE EXTENSION dblink;
\c "RW_THEOPHILE" 
CREATE EXTENSION dblink;
\c "RW_NDABABONYE" 
CREATE EXTENSION dblink;
\c "ASOS_COM" 
CREATE EXTENSION dblink;
\c "ZALANDO" 
CREATE EXTENSION dblink;
\c "CB_ASIA_TPR" 
CREATE EXTENSION dblink;
\c "TENANT2" 
CREATE EXTENSION dblink;
\c "SYNGENTA" 
CREATE EXTENSION dblink;
\c "RW_DAMOURSP" 
CREATE EXTENSION dblink;
\c "RW_MIGNONESP" 
CREATE EXTENSION dblink;
\c "RW_SODOMA" 
CREATE EXTENSION dblink;
\c "RW_KURYAGATANU" 
CREATE EXTENSION dblink;
\c "RW_SGEM" 
CREATE EXTENSION dblink;
\c "RW_PAULHINDIROSP" 
CREATE EXTENSION dblink;
\c "RW_GASIZA" 
CREATE EXTENSION dblink;
\c "RW_THEODOMILE" 
CREATE EXTENSION dblink;
\c "RW_GASANZE" 
CREATE EXTENSION dblink;
\c "RW_MUNYEMANA" 
CREATE EXTENSION dblink;
\c "RW_REALLUCKY" 
CREATE EXTENSION dblink;
\c "RW_BETTY" 
CREATE EXTENSION dblink;
\c "RW_2MBEVERAGES" 
CREATE EXTENSION dblink;
\c "RW_ISABANE" 
CREATE EXTENSION dblink;
\c "RW_KUKANYIRAREBE" 
CREATE EXTENSION dblink;
\c "RW_KARWASA" 
CREATE EXTENSION dblink;
\c "RW_MUKINGA" 
CREATE EXTENSION dblink;
\c "RW_KANSI" 
CREATE EXTENSION dblink;
\c "RW_CHRISTINE" 
CREATE EXTENSION dblink;
\c "RW_NIYOMUREMYI" 
CREATE EXTENSION dblink;
\c "RW_SEBAHAYA" 
CREATE EXTENSION dblink;
\c "RW_FRAICHEUR" 
CREATE EXTENSION dblink;
\c "RW_NSVE" 
CREATE EXTENSION dblink;
\c "RW_DEBANDI" 
CREATE EXTENSION dblink;
\c "RW_MUKO" 
CREATE EXTENSION dblink;
\c "RW_VUNGA" 
CREATE EXTENSION dblink;
\c "RW_THEOBALD" 
CREATE EXTENSION dblink;
\c "RW_NSABIMANA" 
CREATE EXTENSION dblink;
\c "RW_VENUSTE" 
CREATE EXTENSION dblink;
\c "RW_VENERANDA" 
CREATE EXTENSION dblink;
\c "RW_BAPTISTE" 
CREATE EXTENSION dblink;
\c "RW_SPGAHARA" 
CREATE EXTENSION dblink;
\c "RW_POINTBUNGWESP" 
CREATE EXTENSION dblink;
\c "RW_JANJA" 
CREATE EXTENSION dblink;
\c "RW_KIVURUGA" 
CREATE EXTENSION dblink;
\c "RW_RUKURA" 
CREATE EXTENSION dblink;
\c "RW_NEMBA" 
CREATE EXTENSION dblink;
\c "RW_VEDASTE" 
CREATE EXTENSION dblink;
\c "RW_MUGWIZA" 
CREATE EXTENSION dblink;
\c "RW_EUGENE" 
CREATE EXTENSION dblink;
\c "RW_NYANGA" 
CREATE EXTENSION dblink;
\c "RW_RUYENZI" 
CREATE EXTENSION dblink;
\c "RW_KIBOKE" 
CREATE EXTENSION dblink;
\c "LEVI_MONOPRIX" 
CREATE EXTENSION dblink;
\c "MAILLOCHON" 
CREATE EXTENSION dblink;
\c "PC_AUSTRIA" 
CREATE EXTENSION dblink;
\c "PC_GERMANY" 
CREATE EXTENSION dblink;
\c "UAB_NIGINTOS" 
CREATE EXTENSION dblink;
\c "NLY_SCANDINAVIA" 
CREATE EXTENSION dblink;
\c "CCV_SAS" 
CREATE EXTENSION dblink;
\c "GRACIEN_GIHARA_SP" 
CREATE EXTENSION dblink;
\c "NDUBA_SP" 
CREATE EXTENSION dblink;
\c "NYABITARE_SP" 
CREATE EXTENSION dblink;
\c "RW_BWIZA" 
CREATE EXTENSION dblink;
\c "RW_CANTINE_KANA" 
CREATE EXTENSION dblink;
\c "RW_FABRICE" 
CREATE EXTENSION dblink;
\c "RW_GASOGI" 
CREATE EXTENSION dblink;
\c "SP_ZINIYA" 
CREATE EXTENSION dblink;
\c "STOCK_POINT_NYARUTARAMA" 
CREATE EXTENSION dblink;
\c "SOLINE_SP" 
CREATE EXTENSION dblink;
\c "STOCK_POINT_GASANZE" 
CREATE EXTENSION dblink;
\c "SURUTANI_SP" 
CREATE EXTENSION dblink;
\c "DIAGEO_PH" 
CREATE EXTENSION dblink;
\c "DIAGEO_KA" 
CREATE EXTENSION dblink;
\c "DIAGEO_JP" 
CREATE EXTENSION dblink;
\c "TENANT1" 
CREATE EXTENSION dblink;
\c "BOOZT" 
CREATE EXTENSION dblink;
\c "HNK_GDF_BSGLOBAL" 
CREATE EXTENSION dblink;
\c "HNK_GDF_CARISAM" 
CREATE EXTENSION dblink;
\c "WEHKAMP_CENTRAL" 
CREATE EXTENSION dblink;
\c "MDLZ_ITALY_NLSEN_PUB" 
CREATE EXTENSION dblink;
\c "MDLZ_ITALY_NLSEN_SUB" 
CREATE EXTENSION dblink;
\c "MDLZ_PH_SIF" 
CREATE EXTENSION dblink;
\c "TU_EL_BARAKA" 
CREATE EXTENSION dblink;
\c "RW_QUICKMASTER" 
CREATE EXTENSION dblink;
\c "RW_BWERAMVURA" 
CREATE EXTENSION dblink;
\c "RW_CHRISTINEPOINTSP" 
CREATE EXTENSION dblink;
\c "RW_JPIERRE" 
CREATE EXTENSION dblink;
\c "RW_LEONCIESP" 
CREATE EXTENSION dblink;
\c "RW_GASHANGIRO" 
CREATE EXTENSION dblink;
\c "RW_NYARWONDO" 
CREATE EXTENSION dblink;
\c "RW_KINIGI" 
CREATE EXTENSION dblink;
\c "RW_SOLANGE" 
CREATE EXTENSION dblink;
\c "RW_THEOGENE" 
CREATE EXTENSION dblink;
\c "RW_CALANDA" 
CREATE EXTENSION dblink;
\c "RW_GJK" 
CREATE EXTENSION dblink;
\c "RW_KABUGA" 
CREATE EXTENSION dblink;
\c "RW_EASY" 
CREATE EXTENSION dblink;
\c "LEVI_CANADA" 
CREATE EXTENSION dblink;
\c "LOREAL_USA_HEB" 
CREATE EXTENSION dblink;
\c "LOREAL_USA_MEIJER" 
CREATE EXTENSION dblink;
\c "LOREAL_USA_CVS" 
CREATE EXTENSION dblink;
\c "LOREAL_USA_WALMART" 
CREATE EXTENSION dblink;
\c "LOREAL_USA_WALGREENS" 
CREATE EXTENSION dblink;
\c "LOREAL_USA_TARGET" 
CREATE EXTENSION dblink;
\c "LOREAL_USA_RITEAID" 
CREATE EXTENSION dblink;
\c "LOREAL_USA_RETAILERDW" 
CREATE EXTENSION dblink;
\c "LOREAL_USA_DOLGEN" 
CREATE EXTENSION dblink;
\c "LOREAL_USA_KROGER" 
CREATE EXTENSION dblink;
\c "LOREAL_USA_AMAZON" 
CREATE EXTENSION dblink;
\c "LOREAL_USA_ULTA" 
CREATE EXTENSION dblink;
\c "LOREAL_USA_RETAILERDW_EXTENDED_1" 
CREATE EXTENSION dblink;
\c "" 
CREATE EXTENSION dblink;
