\c "7147_COMA_MX" 
CREATE EXTENSION dblink;
\c "7137_SURTIFAMILIAR_CO" 
CREATE EXTENSION dblink;
\c "7139_COMFANDI_CO" 
CREATE EXTENSION dblink;
\c "7140_MERCAMIO_CO" 
CREATE EXTENSION dblink;
\c "7141_MERCATODOCF_CO" 
CREATE EXTENSION dblink;
\c "7142_MEGATIENDAS_CO" 
CREATE EXTENSION dblink;
\c "7143_ADELCO_MX" 
CREATE EXTENSION dblink;
\c "7144_ANICETOS_MX" 
CREATE EXTENSION dblink;
\c "7108_EXTRA_FARMA" 
CREATE EXTENSION dblink;
\c "7110_PAGUE_MENOS" 
CREATE EXTENSION dblink;
\c "7112_MUFFATO" 
CREATE EXTENSION dblink;
\c "7113_ANGELONI" 
CREATE EXTENSION dblink;
\c "7114_GIASSI" 
CREATE EXTENSION dblink;
\c "7116_SUPER_PM" 
CREATE EXTENSION dblink;
\c "7117_COOP" 
CREATE EXTENSION dblink;
\c "7118_CONFIANCA" 
CREATE EXTENSION dblink;
\c "7119_SAVEGNAGO" 
CREATE EXTENSION dblink;
\c "7121_LOPES" 
CREATE EXTENSION dblink;
\c "7122_D_AVO" 
CREATE EXTENSION dblink;
\c "7123_SPAR_HU" 
CREATE EXTENSION dblink;
\c "7127_FEEDO_CZ" 
CREATE EXTENSION dblink;
\c "7146_CHAPA_MX" 
CREATE EXTENSION dblink;
\c "7148_CORVI_MX" 
CREATE EXTENSION dblink;
\c "7149_CVS_MX" 
CREATE EXTENSION dblink;
\c "7150_DAPSA_MX" 
CREATE EXTENSION dblink;
\c "7154_HUGOS_MX" 
CREATE EXTENSION dblink;
\c "7156_LECHE_19_H_MX" 
CREATE EXTENSION dblink;
\c "7158_PANADERO_MX" 
CREATE EXTENSION dblink;
\c "7165_PANALERANORTE_AR" 
CREATE EXTENSION dblink;
\c "7166_MAYORSUR_AR" 
CREATE EXTENSION dblink;
\c "7167_UPA_AR" 
CREATE EXTENSION dblink;
\c "7172_NISSEI_BR" 
CREATE EXTENSION dblink;
\c "7174_SONDA_BR" 
CREATE EXTENSION dblink;
\c "7177_ATAKAREJO_BR" 
CREATE EXTENSION dblink;
\c "7178_COMERCIALMORRINHO_BR" 
CREATE EXTENSION dblink;
\c "7181_FORTATACADISTAMS_BR" 
CREATE EXTENSION dblink;
\c "7182_JAD_ZOGHEIB_BR" 
CREATE EXTENSION dblink;
\c "7185_LUIZ_TONIN_BR" 
CREATE EXTENSION dblink;
\c "7186_FORT_ATACADISTAMT_BR" 
CREATE EXTENSION dblink;
\c "7187_ONOFRE_BR" 
CREATE EXTENSION dblink;
\c "7188_COMPER_DF_GO_BR" 
CREATE EXTENSION dblink;
\c "7138_CANAVERAL_CO" 
CREATE EXTENSION dblink;
\c "7190_ABASTECEDERO_MX" 
CREATE EXTENSION dblink;
\c "7191_ABARROTERA_MX" 
CREATE EXTENSION dblink;
\c "7192_DAVATTA_MX" 
CREATE EXTENSION dblink;
\c "7193_MERCADO_MX" 
CREATE EXTENSION dblink;
\c "7194_MAKRO_PE" 
CREATE EXTENSION dblink;
\c "7195_CORPORACION_PE" 
CREATE EXTENSION dblink;
\c "7196_MAYORSA_PE" 
CREATE EXTENSION dblink;
\c "3876_COMPER_BR" 
CREATE EXTENSION dblink;
\c "3877_MAKRO_BR" 
CREATE EXTENSION dblink;
\c "3870_SODIMAC_PE" 
CREATE EXTENSION dblink;
\c "3871_PROMART_PE" 
CREATE EXTENSION dblink;
\c "3873_LADMAR_LA" 
CREATE EXTENSION dblink;
\c "3874_CSD_BR" 
CREATE EXTENSION dblink;
\c "7152_SU_SUPER_MX" 
CREATE EXTENSION dblink;
\c "7183_SOCOFAR_DISTRIBUCION_CL" 
CREATE EXTENSION dblink;
\c "7188_SODIMAC_CL" 
CREATE EXTENSION dblink;
\c "7198_MAKRO_ZA" 
CREATE EXTENSION dblink;
\c "7199_LUPARELLO_AR" 
CREATE EXTENSION dblink;
\c "7170_REDE_BH_BR" 
CREATE EXTENSION dblink;
\c "7219_CARREFOUR_EG" 
CREATE EXTENSION dblink;
\c "7220_ABUDHABI_COOP_AP" 
CREATE EXTENSION dblink;
\c "3900_MERCATOR_SERBIA" 
CREATE EXTENSION dblink;
\c "3901_UTKONOS_RU" 
CREATE EXTENSION dblink;
\c "3897_MAGNUM_KAZ" 
CREATE EXTENSION dblink;
\c "3898_SKIF_KAZ" 
CREATE EXTENSION dblink;
\c "3892_GESA_PE" 
CREATE EXTENSION dblink;
\c "3890_COOP_SAPPORO_JP" 
CREATE EXTENSION dblink;
\c "3891_DPSP_BR" 
CREATE EXTENSION dblink;
\c "7207_BOLCOM_NL" 
CREATE EXTENSION dblink;
\c "7208_SYSTEM_U_NL" 
CREATE EXTENSION dblink;
\c "7218_BIEDRONKA_PL" 
CREATE EXTENSION dblink;
\c "PNG_LA" 
CREATE EXTENSION dblink;
\c "PNG_ASIA" 
CREATE EXTENSION dblink;
\c "PNG_CE" 
CREATE EXTENSION dblink;
\c "3848_DETS_MIR_RU" 
CREATE EXTENSION dblink;
\c "3853_GROCERS_US" 
CREATE EXTENSION dblink;
\c "7066_FRMCS_DEL_AH_MX" 
CREATE EXTENSION dblink;
\c "7115_CSD" 
CREATE EXTENSION dblink;
\c "3895_AUCHAN_HUNGARY" 
CREATE EXTENSION dblink;
\c "3896_AUCHAN_POLAND" 
CREATE EXTENSION dblink;
\c "3688_AUCHAN_ROU" 
CREATE EXTENSION dblink;
\c "3902_BTT_TR" 
CREATE EXTENSION dblink;
\c "3903_GENKY" 
CREATE EXTENSION dblink;
\c "3904_COSTCO" 
CREATE EXTENSION dblink;
\c "3905_COUPANG" 
CREATE EXTENSION dblink;
\c "3906_EUROPHARMA_KAZ" 
CREATE EXTENSION dblink;
\c "3907_TOI_MART_KAZ" 
CREATE EXTENSION dblink;
\c "7221_PRICEMART_LADMAR" 
CREATE EXTENSION dblink;
\c "7223_ALLEGRO_PL" 
CREATE EXTENSION dblink;
\c "7224_NAZUBY_CZ" 
CREATE EXTENSION dblink;
\c "3893_NATIONAL_IRI_GFK_DE" 
CREATE EXTENSION dblink;
\c "3908_CLAS_OHLSON" 
CREATE EXTENSION dblink;
\c "3910_REMA_NO" 
CREATE EXTENSION dblink;
\c "3916_AMAZON_NL" 
CREATE EXTENSION dblink;
\c "7169_FARMACITY_AR" 
CREATE EXTENSION dblink;
\c "3917_PROVERA_EU" 
CREATE EXTENSION dblink;
\c "3918_CARREFOUR_FR" 
CREATE EXTENSION dblink;
\c "3920_COMMERCIAL_ZAFFARI_BR" 
CREATE EXTENSION dblink;
\c "3919_AHOLD_NL" 
CREATE EXTENSION dblink;
\c "7205_FARMACIE_IN_CHIARO_IT" 
CREATE EXTENSION dblink;
\c "7057_CONTROL_MX" 
CREATE EXTENSION dblink;
\c "7128_MERCASUR_CO" 
CREATE EXTENSION dblink;
\c "7129_LA_QUINTA_CO" 
CREATE EXTENSION dblink;
\c "7130_MARIO_HERNANDEZ_CO" 
CREATE EXTENSION dblink;
\c "7131_PARAISO_CO" 
CREATE EXTENSION dblink;
\c "7132_EURO_CO" 
CREATE EXTENSION dblink;
\c "7133_PASADENA_CO" 
CREATE EXTENSION dblink;
\c "7134_ZAPATOCA_CO" 
CREATE EXTENSION dblink;
\c "7135_MERCACENTRO_CO" 
CREATE EXTENSION dblink;
\c "7136_EPM_CO" 
CREATE EXTENSION dblink;
\c "7161_ZORRO_MX" 
CREATE EXTENSION dblink;
\c "7189_CAGSA_MX" 
CREATE EXTENSION dblink;
\c "7197_LA_CANASTA_CO" 
CREATE EXTENSION dblink;
\c "7162_DIARCO_AR" 
CREATE EXTENSION dblink;
\c "7163_MAXI_AR" 
CREATE EXTENSION dblink;
\c "7164_MAYCAR_AR" 
CREATE EXTENSION dblink;
\c "7168_NINI_AR" 
CREATE EXTENSION dblink;
\c "3899_DETSKI_MIR_KAZ" 
CREATE EXTENSION dblink;
\c "PNG_BRAZIL" 
CREATE EXTENSION dblink;
\c "PNG_EE" 
CREATE EXTENSION dblink;
\c "3850_EMAG_RO" 
CREATE EXTENSION dblink;
\c "7009_EXITOCATMAN_CO" 
CREATE EXTENSION dblink;
\c "7053_SORIANACATMAN" 
CREATE EXTENSION dblink;
\c "7056_CNDCATMAN_CO" 
CREATE EXTENSION dblink;
\c "7059_AMAZON_MX" 
CREATE EXTENSION dblink;
\c "3733_WOOLWORTHS_AU" 
CREATE EXTENSION dblink;
\c "7065_OXXO_MX" 
CREATE EXTENSION dblink;
\c "3894_AMAZONCOM_EU_ABVP" 
CREATE EXTENSION dblink;
\c "3483_WALGREENS_US" 
CREATE EXTENSION dblink;
\c "3867_DROGAL_BR" 
CREATE EXTENSION dblink;
\c "7092_VISHAL" 
CREATE EXTENSION dblink;
\c "7093_REL_RETAIL" 
CREATE EXTENSION dblink;
\c "7094_REL_CC" 
CREATE EXTENSION dblink;
\c "7101_WALMART" 
CREATE EXTENSION dblink;
\c "7104_WOOLWORTHS" 
CREATE EXTENSION dblink;
\c "7103_DPSP" 
CREATE EXTENSION dblink;
\c "7102_BIGW" 
CREATE EXTENSION dblink;
\c "7096_SPAR" 
CREATE EXTENSION dblink;
\c "7099_DABUR" 
CREATE EXTENSION dblink;
\c "7089_FUTURE_RETAIL" 
CREATE EXTENSION dblink;
\c "7090_APOLLO" 
CREATE EXTENSION dblink;
\c "7124_HEBE_PL" 
CREATE EXTENSION dblink;
\c "3667_SAMS_CATMAN_US" 
CREATE EXTENSION dblink;
\c "7206_CESAR_ACQUA_SAPONE_IT" 
CREATE EXTENSION dblink;
\c "PNG_TC_ASEAN_MSR_EAN" 
CREATE EXTENSION dblink;
\c "PNG_TC_ASEAN_SS_PROD" 
CREATE EXTENSION dblink;
\c "3888_REWE_CM_AT" 
CREATE EXTENSION dblink;
\c "1434_SAMS_PG" 
CREATE EXTENSION dblink;
\c "7125_NATURA_PL" 
CREATE EXTENSION dblink;
\c "3883_COSTCO_US" 
CREATE EXTENSION dblink;
\c "3884_COSTCO_CA" 
CREATE EXTENSION dblink;
\c "PNG_CANADA" 
CREATE EXTENSION dblink;
\c "PNG_UK" 
CREATE EXTENSION dblink;
\c "3823_SUPERSOL_SPAIN" 
CREATE EXTENSION dblink;
\c "3830_LOBLAW_CA" 
CREATE EXTENSION dblink;
\c "3831_SDM_CATMAN_CA" 
CREATE EXTENSION dblink;
\c "3843_HOME_DEPOT_CA" 
CREATE EXTENSION dblink;
\c "7102_BIG_W" 
CREATE EXTENSION dblink;
\c "3885_WAITROSE_UK" 
CREATE EXTENSION dblink;
\c "3825_JERONIMO_PORGL" 
CREATE EXTENSION dblink;
\c "7100_HERITAGE" 
CREATE EXTENSION dblink;
\c "7091_HG" 
CREATE EXTENSION dblink;
\c "7095_ABRL_HYPER" 
CREATE EXTENSION dblink;
\c "7097_ABRL_LMM" 
CREATE EXTENSION dblink;
\c "3879_AMAZON_IT" 
CREATE EXTENSION dblink;
\c "3880_AMAZON_ES" 
CREATE EXTENSION dblink;
\c "3837_TOMODS_JP" 
CREATE EXTENSION dblink;
\c "PNG_JAPAN" 
CREATE EXTENSION dblink;
\c "PNG_IMEA" 
CREATE EXTENSION dblink;
\c "3829_SEKI_YAKUHIN_JP" 
CREATE EXTENSION dblink;
\c "3834_COCOKARA_JP" 
CREATE EXTENSION dblink;
\c "3836_TSURUHA_JP" 
CREATE EXTENSION dblink;
\c "3839_VALOR_JP" 
CREATE EXTENSION dblink;
\c "3840_KOMERI_JP" 
CREATE EXTENSION dblink;
\c "3869_SHIMACHU_JP" 
CREATE EXTENSION dblink;
\c "3882_FUJIYAKUHIN_JP" 
CREATE EXTENSION dblink;
\c "3827_CAINZ_JP" 
CREATE EXTENSION dblink;
\c "3828_INAGEYA_JP" 
CREATE EXTENSION dblink;
\c "3832_LIFE_JP" 
CREATE EXTENSION dblink;
\c "3833_SUGI_YN_JP" 
CREATE EXTENSION dblink;
\c "7200_UNION_COOP_AP" 
CREATE EXTENSION dblink;
\c "7201_DANUBE_AP" 
CREATE EXTENSION dblink;
\c "7202_BIN_DAWOOD_AP" 
CREATE EXTENSION dblink;
\c "7203_KM_TRADING_AP" 
CREATE EXTENSION dblink;
\c "7204_AL_MAYA_AP" 
CREATE EXTENSION dblink;
\c "PNG_WE" 
CREATE EXTENSION dblink;
\c "" 
CREATE EXTENSION dblink;
