\c "AHOLD_CZECH" 
CREATE EXTENSION dblink;
\c "3893_IRI_DE" 
CREATE EXTENSION dblink;
\c "3607_DIXI_RU" 
CREATE EXTENSION dblink;
\c "3267_ASDA_UK" 
CREATE EXTENSION dblink;
\c "3317_CAREFOUR_BE" 
CREATE EXTENSION dblink;
\c "3412_DIA_GLOBAL" 
CREATE EXTENSION dblink;
\c "GLOBUS_CZECH" 
CREATE EXTENSION dblink;
\c "3636_ROBINSONS_PH" 
CREATE EXTENSION dblink;
\c "3646_CARREFOUR_GLOBAL" 
CREATE EXTENSION dblink;
\c "3648_MYMARKET_GR" 
CREATE EXTENSION dblink;
\c "7211_INDEPENDENTS_BANNER_AU" 
CREATE EXTENSION dblink;
\c "2574_TRADE_INVENTORY_CES" 
CREATE EXTENSION dblink;
\c "3845_BIG_LOTS_US" 
CREATE EXTENSION dblink;
\c "3846_AMAZON_ABVP_US" 
CREATE EXTENSION dblink;
\c "1642_MIGROS_TR" 
CREATE EXTENSION dblink;
\c "3042_PRESTIGE_KRUIDVAT_NL" 
CREATE EXTENSION dblink;
\c "7212_ALDI_ESTIMATE_BANNER_AU" 
CREATE EXTENSION dblink;
\c "7214_PRICELINE_BANNER_AU" 
CREATE EXTENSION dblink;
\c "7213_MY_CHEMIST_GROUP_BANNER_AU" 
CREATE EXTENSION dblink;
\c "7210_COLES_GROUP_BANNER_AU" 
CREATE EXTENSION dblink;
\c "1890_MULTICUSTOMER_UA" 
CREATE EXTENSION dblink;
\c "7215_COUNTDOWN_BANNER_NZ" 
CREATE EXTENSION dblink;
\c "DM_HUNGARY" 
CREATE EXTENSION dblink;
\c "DM_SLOVAKIA" 
CREATE EXTENSION dblink;
\c "3804_SUGI_YAKKYOKU_JP" 
CREATE EXTENSION dblink;
\c "3805_WELCIA_JP" 
CREATE EXTENSION dblink;
\c "3806_TRIAL_JP" 
CREATE EXTENSION dblink;
\c "METRO_HUNGARY" 
CREATE EXTENSION dblink;
\c "3782_LOBLAWS_CA" 
CREATE EXTENSION dblink;
\c "3785_BJS_US" 
CREATE EXTENSION dblink;
\c "3780_ATACADAO_BR" 
CREATE EXTENSION dblink;
\c "3786_MAICAO_CL" 
CREATE EXTENSION dblink;
\c "3794_KIRINDO_JP" 
CREATE EXTENSION dblink;
\c "3795_ZAGZAG_JP" 
CREATE EXTENSION dblink;
\c "3793_CHUBU_JP" 
CREATE EXTENSION dblink;
\c "3808_EURONICS_DE" 
CREATE EXTENSION dblink;
\c "93655_GADISA_SPAIN" 
CREATE EXTENSION dblink;
\c "CES_INVENTORY" 
CREATE EXTENSION dblink;
\c "CUSTOMER_LA" 
CREATE EXTENSION dblink;
\c "CUSTOMER_EU" 
CREATE EXTENSION dblink;
\c "QUIDSI_US_ECOMM" 
CREATE EXTENSION dblink;
\c "2715_HOMEDEPOT_US" 
CREATE EXTENSION dblink;
\c "3377_OTHIAM_AP" 
CREATE EXTENSION dblink;
\c "2751_ROSSMANN_PL" 
CREATE EXTENSION dblink;
\c "3598_DIA_DIA_VE" 
CREATE EXTENSION dblink;
\c "3617_EROSKI_SP" 
CREATE EXTENSION dblink;
\c "3624_YUTAKA_PHARMACY_JP" 
CREATE EXTENSION dblink;
\c "3634_CARREFOUR_MO" 
CREATE EXTENSION dblink;
\c "3690_LA_ANONIMA_CATMAN_AR" 
CREATE EXTENSION dblink;
\c "3737_PICK_N_PAY_SA" 
CREATE EXTENSION dblink;
\c "3742_SOBEYS_CA" 
CREATE EXTENSION dblink;
\c "3746_D_ARAUJO_BR" 
CREATE EXTENSION dblink;
\c "3747_SUPERPAGUEMENOS_BR" 
CREATE EXTENSION dblink;
\c "3748_ICA_SE" 
CREATE EXTENSION dblink;
\c "3767_IRMAOS_L_BR" 
CREATE EXTENSION dblink;
\c "1314_BJHL_CHINA" 
CREATE EXTENSION dblink;
\c "1898_CARREFOUR_AP" 
CREATE EXTENSION dblink;
\c "3172_MATSUMOTO_JP" 
CREATE EXTENSION dblink;
\c "1664_EMART_KR" 
CREATE EXTENSION dblink;
\c "3642_LOBLAW_CA" 
CREATE EXTENSION dblink;
\c "3650_LOBLAW_CA" 
CREATE EXTENSION dblink;
\c "3730_TARGET_US" 
CREATE EXTENSION dblink;
\c "3585_KROGER_US" 
CREATE EXTENSION dblink;
\c "3640_SDM_CA" 
CREATE EXTENSION dblink;
\c "2561_PRESTIGE_OLD_NAVY_US" 
CREATE EXTENSION dblink;
\c "3318_TANDER_RU" 
CREATE EXTENSION dblink;
\c "3410_CARREFOUR_GLOBAL_MU" 
CREATE EXTENSION dblink;
\c "3240_CAPRABO_EU" 
CREATE EXTENSION dblink;
\c "3580_INTERMARCHE_FR" 
CREATE EXTENSION dblink;
\c "3608_LULU_MU" 
CREATE EXTENSION dblink;
\c "3126_SAINSBURY_UK" 
CREATE EXTENSION dblink;
\c "3268_OCADO_ECOMM_UK" 
CREATE EXTENSION dblink;
\c "3269_BOOTS_ECOMM_UK" 
CREATE EXTENSION dblink;
\c "3338_SELGROS_RO" 
CREATE EXTENSION dblink;
\c "3286_TESCO_ECOMM_UK" 
CREATE EXTENSION dblink;
\c "3032_METRO_UA" 
CREATE EXTENSION dblink;
\c "3444_ABRL_IN" 
CREATE EXTENSION dblink;
\c "3422_LASA_BR" 
CREATE EXTENSION dblink;
\c "3781_ACN_DE_ALDI" 
CREATE EXTENSION dblink;
\c "3184_COOPKIEL_DE" 
CREATE EXTENSION dblink;
\c "3765_CVS_US" 
CREATE EXTENSION dblink;
\c "ALFAMIDI_ID" 
CREATE EXTENSION dblink;
\c "LOTTEMART_ID" 
CREATE EXTENSION dblink;
\c "GIANT_ID" 
CREATE EXTENSION dblink;
\c "GUARDIAN_ID" 
CREATE EXTENSION dblink;
\c "STARMART_ID" 
CREATE EXTENSION dblink;
\c "HERO_ID" 
CREATE EXTENSION dblink;
\c "INDOGROSIR_ID" 
CREATE EXTENSION dblink;
\c "LION_ID" 
CREATE EXTENSION dblink;
\c "INDOMARET_ID" 
CREATE EXTENSION dblink;
\c "MAKRO_ID" 
CREATE EXTENSION dblink;
\c "MATAHARI_ID" 
CREATE EXTENSION dblink;
\c "YOGYA_ID" 
CREATE EXTENSION dblink;
\c "CARREFOUR_ID" 
CREATE EXTENSION dblink;
\c "ALFAMART_ID" 
CREATE EXTENSION dblink;
\c "CUSTOMER_ASIA" 
CREATE EXTENSION dblink;
\c "2541_LA_COMER" 
CREATE EXTENSION dblink;
\c "2542_CHEDRAUI_MX" 
CREATE EXTENSION dblink;
\c "2562_PRESTIGE_NEIMAN_MARCUS_US" 
CREATE EXTENSION dblink;
\c "2577_METRO_RO" 
CREATE EXTENSION dblink;
\c "2709_FARMATODO_VE" 
CREATE EXTENSION dblink;
\c "2738_METRO_IN" 
CREATE EXTENSION dblink;
\c "3028_TESCO_IN" 
CREATE EXTENSION dblink;
\c "3144_METRO_AT" 
CREATE EXTENSION dblink;
\c "3176_EDEKA_DE" 
CREATE EXTENSION dblink;
\c "3189_DRUGSTORE_COM_US" 
CREATE EXTENSION dblink;
\c "3200_BUDNIKOWSKY_DE" 
CREATE EXTENSION dblink;
\c "3204_FEGRO_DE" 
CREATE EXTENSION dblink;
\c "3208_WASGAU_DE" 
CREATE EXTENSION dblink;
\c "3210_DOHLE_DE" 
CREATE EXTENSION dblink;
\c "3211_ACN_DE" 
CREATE EXTENSION dblink;
\c "3216_KARSTADT_DE" 
CREATE EXTENSION dblink;
\c "3246_POSTLOGISTICS_CH" 
CREATE EXTENSION dblink;
\c "3293_AMAZON_COM_FR" 
CREATE EXTENSION dblink;
\c "3313_PERFOGROUP_AR" 
CREATE EXTENSION dblink;
\c "3369_DM_AT" 
CREATE EXTENSION dblink;
\c "3241_CARREFOUR_ES" 
CREATE EXTENSION dblink;
\c "3424_MULTIDRUG_BR" 
CREATE EXTENSION dblink;
\c "3588_BENAVIDES_MX" 
CREATE EXTENSION dblink;
\c "3601_CALIMAX_MX" 
CREATE EXTENSION dblink;
\c "3605_COOP_BR" 
CREATE EXTENSION dblink;
\c "3606_NORDESTAO_BR" 
CREATE EXTENSION dblink;
\c "3628_CASA_LEY_MX" 
CREATE EXTENSION dblink;
\c "3633_PAGUEMENOS_BR" 
CREATE EXTENSION dblink;
\c "3635_CENCOSUD_BR" 
CREATE EXTENSION dblink;
\c "3709_CONDOR_BR" 
CREATE EXTENSION dblink;
\c "3721_ANGELONI_BR" 
CREATE EXTENSION dblink;
\c "3727_BAHAMAS_BR" 
CREATE EXTENSION dblink;
\c "1666_EXITO_CO" 
CREATE EXTENSION dblink;
\c "1879_TESCO_KR" 
CREATE EXTENSION dblink;
\c "1880_LOTTEMART_KR" 
CREATE EXTENSION dblink;
\c "3649_UNIDASUL_BR" 
CREATE EXTENSION dblink;
\c "3658_COLES_AU" 
CREATE EXTENSION dblink;
\c "3659_COSTCO_MX" 
CREATE EXTENSION dblink;
\c "2712_MAKRO_CO" 
CREATE EXTENSION dblink;
\c "2713_OLIMPICA_CO" 
CREATE EXTENSION dblink;
\c "2741_CENCOSUD_PE" 
CREATE EXTENSION dblink;
\c "2742_ECKERD_PE" 
CREATE EXTENSION dblink;
\c "3149_METRO_DAILY_DE" 
CREATE EXTENSION dblink;
\c "3178_GLOBUS_DE" 
CREATE EXTENSION dblink;
\c "3202_ROSSMANN_DE" 
CREATE EXTENSION dblink;
\c "3233_DM_DE" 
CREATE EXTENSION dblink;
\c "3332_CENCOSUD_AR" 
CREATE EXTENSION dblink;
\c "3335_COOPERATIVE_OBRERA_AR" 
CREATE EXTENSION dblink;
\c "3484_MEIJER_US" 
CREATE EXTENSION dblink;
\c "2545_CARREFOUR_RO" 
CREATE EXTENSION dblink;
\c "2586_CARREFOUR_TR" 
CREATE EXTENSION dblink;
\c "2736_CARREFOUR_GR" 
CREATE EXTENSION dblink;
\c "3027_BIG_BAZAAR_IN" 
CREATE EXTENSION dblink;
\c "3047_AXFOOD_SE" 
CREATE EXTENSION dblink;
\c "3123_COOP_DK" 
CREATE EXTENSION dblink;
\c "3242_ALCAMPO_ES" 
CREATE EXTENSION dblink;
\c "3243_MERCADONA_ES" 
CREATE EXTENSION dblink;
\c "3244_ECI_DEPTILN_ES" 
CREATE EXTENSION dblink;
\c "3651_DFI_PH" 
CREATE EXTENSION dblink;
\c "3656_SKLAVENITIS_GR" 
CREATE EXTENSION dblink;
\c "3661_WATSONS_PH" 
CREATE EXTENSION dblink;
\c "3664_GALAXIAS_GR" 
CREATE EXTENSION dblink;
\c "3680_AUCHAN_FR" 
CREATE EXTENSION dblink;
\c "3681_AUCHAN_RU" 
CREATE EXTENSION dblink;
\c "3682_AUCHAN_IT" 
CREATE EXTENSION dblink;
\c "3687_AUCHAN_ES" 
CREATE EXTENSION dblink;
\c "3744_X5_RU" 
CREATE EXTENSION dblink;
\c "3762_MEGAIMAGE_RO" 
CREATE EXTENSION dblink;
\c "CARREFOUR_POLAND" 
CREATE EXTENSION dblink;
\c "TESCO_HUNGARY" 
CREATE EXTENSION dblink;
\c "DM_CROATIA" 
CREATE EXTENSION dblink;
\c "MULLER_HUNGARY" 
CREATE EXTENSION dblink;
\c "SELGROS_POLAND" 
CREATE EXTENSION dblink;
\c "TESCO_POLAND" 
CREATE EXTENSION dblink;
\c "TESCO_SLOVAKIA" 
CREATE EXTENSION dblink;
\c "TESCO_CZECH" 
CREATE EXTENSION dblink;
\c "DM_CZECH" 
CREATE EXTENSION dblink;
\c "ALZA_CZECH" 
CREATE EXTENSION dblink;
\c "ALZA_SLOVAKIA" 
CREATE EXTENSION dblink;
\c "KONZUM_CROATIA" 
CREATE EXTENSION dblink;
\c "LECLERC_POLAND" 
CREATE EXTENSION dblink;
\c "PK_SLOVAKIA" 
CREATE EXTENSION dblink;
\c "ROSSMANN_HUNGARY" 
CREATE EXTENSION dblink;
\c "3774_DIA_BR" 
CREATE EXTENSION dblink;
\c "3775_TOTTUS_CL" 
CREATE EXTENSION dblink;
\c "3776_HARRIS_TEETER" 
CREATE EXTENSION dblink;
\c "3777_SDM" 
CREATE EXTENSION dblink;
\c "3778_AI_SUPER_MX" 
CREATE EXTENSION dblink;
\c "ROSSMANN_POLAND" 
CREATE EXTENSION dblink;
\c "3788_PANDA_SAUDI" 
CREATE EXTENSION dblink;
\c "3789_AMAZON_US" 
CREATE EXTENSION dblink;
\c "3790_CREATE_JP" 
CREATE EXTENSION dblink;
\c "93632_SUPERSOL_SPAIN" 
CREATE EXTENSION dblink;
\c "93237_JERONIMO_PORGL" 
CREATE EXTENSION dblink;
\c "93732_INTERMAR_PORT" 
CREATE EXTENSION dblink;
\c "93600_CONDOR_DUP_BR" 
CREATE EXTENSION dblink;
\c "93594_LIMPIATODO_VEN" 
CREATE EXTENSION dblink;
\c "93596_SUPER_TIEND_LA" 
CREATE EXTENSION dblink;
\c "93154_CFR_DUP_BR" 
CREATE EXTENSION dblink;
\c "93153_CASINO_BR_GPA" 
CREATE EXTENSION dblink;
\c "93446_DROGARA_CAT_BR" 
CREATE EXTENSION dblink;
\c "93336_DANSK_DENMARK" 
CREATE EXTENSION dblink;
\c "3810_ARKLAND_SAKAMOT" 
CREATE EXTENSION dblink;
\c "3811_DONKIJOTE" 
CREATE EXTENSION dblink;
\c "3812_ELEVEN_DRUGS" 
CREATE EXTENSION dblink;
\c "3751_FCL_CA" 
CREATE EXTENSION dblink;
\c "1561_PREUNIC_CL" 
CREATE EXTENSION dblink;
\c "1562_FASA_CL" 
CREATE EXTENSION dblink;
\c "1563_SOCOFAR_CL" 
CREATE EXTENSION dblink;
\c "3184_REWE_DE" 
CREATE EXTENSION dblink;
\c "1565_SYB_FARMA_CL" 
CREATE EXTENSION dblink;
\c "1578_TOYS_R_US_JP" 
CREATE EXTENSION dblink;
\c "1588_DCM_JP" 
CREATE EXTENSION dblink;
\c "1878_PROVERA_FR" 
CREATE EXTENSION dblink;
\c "1903_KOHNAN_JP" 
CREATE EXTENSION dblink;
\c "3039_SPENCER_IN" 
CREATE EXTENSION dblink;
\c "PNG" 
CREATE EXTENSION dblink;
\c "3813_KUSURI_NA_AOKI" 
CREATE EXTENSION dblink;
\c "3814_SAPPORO_DRUG" 
CREATE EXTENSION dblink;
\c "3815_LOHACO" 
CREATE EXTENSION dblink;
\c "3818_WALMART_CATMAN" 
CREATE EXTENSION dblink;
\c "3844_AMAZON_US" 
CREATE EXTENSION dblink;
\c "AMAZON_FR_ECOMM" 
CREATE EXTENSION dblink;
\c "DRUGSTORE_US_ECOMM" 
CREATE EXTENSION dblink;
\c "MYWEBGROCER_USA_ECOMM" 
CREATE EXTENSION dblink;
\c "LECLERC_FR" 
CREATE EXTENSION dblink;
\c "3211_GFK_DE" 
CREATE EXTENSION dblink;
\c "LA14_CATMAN_CO" 
CREATE EXTENSION dblink;
\c "DIA_GLOBAL" 
CREATE EXTENSION dblink;
\c "FTMG_METRO_BG" 
CREATE EXTENSION dblink;
\c "3740_FAMILYDOLLAR_US" 
CREATE EXTENSION dblink;
\c "3758_SAFEWAY_CA" 
CREATE EXTENSION dblink;
\c "3187_TARGET_ECOMM_US" 
CREATE EXTENSION dblink;
\c "3701_TENGELMANN_DE" 
CREATE EXTENSION dblink;
\c "3722_MILLAN_AR" 
CREATE EXTENSION dblink;
\c "3731_PAM_IT" 
CREATE EXTENSION dblink;
\c "3738_KROGER_US" 
CREATE EXTENSION dblink;
\c "3618_CARREFOUR_IT" 
CREATE EXTENSION dblink;
\c "2572_SORIANA_MX" 
CREATE EXTENSION dblink;
\c "1668_CENCOSUD_CO" 
CREATE EXTENSION dblink;
\c "3141_AMAZON_ECOMM_US" 
CREATE EXTENSION dblink;
\c "3769_EXPERT_DE" 
CREATE EXTENSION dblink;
\c "PNG_DACH" 
CREATE EXTENSION dblink;
\c "3713_DIA_AR" 
CREATE EXTENSION dblink;
\c "3759_ABDELHAIZE_GR" 
CREATE EXTENSION dblink;
\c "3770_MASOUTIS_GR" 
CREATE EXTENSION dblink;
\c "3764_KROGER_US" 
CREATE EXTENSION dblink;
\c "3190_QUIDSI_COM_US" 
CREATE EXTENSION dblink;
\c "3337_MARJANE_MO" 
CREATE EXTENSION dblink;
\c "3702_LOWES_US" 
CREATE EXTENSION dblink;
\c "3726_MENARDS_US" 
CREATE EXTENSION dblink;
\c "3750_DOLLARAMA_CA" 
CREATE EXTENSION dblink;
\c "3752_KATZ_CA" 
CREATE EXTENSION dblink;
\c "3754_OFG_CA" 
CREATE EXTENSION dblink;
\c "3755_LONDONDRUGS_CA" 
CREATE EXTENSION dblink;
\c "3756_CTC_CA" 
CREATE EXTENSION dblink;
\c "3757_AMAZON_CA" 
CREATE EXTENSION dblink;
\c "3679_ABBAT_RU" 
CREATE EXTENSION dblink;
\c "3220_UNIPRIX_CA" 
CREATE EXTENSION dblink;
\c "2566_PRESTIGE_LORD_TAYLOR_US" 
CREATE EXTENSION dblink;
\c "2567_PRESTIGE_SEPHORA_US" 
CREATE EXTENSION dblink;
\c "2568_PRESTIGE_NORDSTROM_US" 
CREATE EXTENSION dblink;
\c "3230_ESSELUNGA_IT" 
CREATE EXTENSION dblink;
\c "3291_AMAZON_UK" 
CREATE EXTENSION dblink;
\c "3292_AMAZON_DK" 
CREATE EXTENSION dblink;
\c "3031_CORA_RO" 
CREATE EXTENSION dblink;
\c "2583_SPSA_PE" 
CREATE EXTENSION dblink;
\c "3037_BERGENDAHLS_SE" 
CREATE EXTENSION dblink;
\c "1867_CENCOSUD_CL" 
CREATE EXTENSION dblink;
\c "1896_PRESTIGE_FEDERATED_US" 
CREATE EXTENSION dblink;
\c "3146_REWE_AT" 
CREATE EXTENSION dblink;
\c "3147_MEDIA_MARKET_AT" 
CREATE EXTENSION dblink;
\c "3148_SPAR_AT" 
CREATE EXTENSION dblink;
\c "3174_MIGROS_CH" 
CREATE EXTENSION dblink;
\c "2548_TESCO_UK" 
CREATE EXTENSION dblink;
\c "2573_HEB_MX" 
CREATE EXTENSION dblink;
\c "2716_MORISSONS_UK" 
CREATE EXTENSION dblink;
\c "2755_CARREFOUR_BR" 
CREATE EXTENSION dblink;
\c "3030_GPA_BR" 
CREATE EXTENSION dblink;
\c "3044_SMU_UNIMARC_CL" 
CREATE EXTENSION dblink;
\c "3236_SONAE_PT" 
CREATE EXTENSION dblink;
\c "1904_GS_MART_KR" 
CREATE EXTENSION dblink;
\c "2553_LA14_CO" 
CREATE EXTENSION dblink;
\c "2584_TOTTUS_PE" 
CREATE EXTENSION dblink;
\c "2711_ALKOSTO_CO" 
CREATE EXTENSION dblink;
\c "3638_D_AVO_BR" 
CREATE EXTENSION dblink;
\c "3639_SAVEGNAGO_BR" 
CREATE EXTENSION dblink;
\c "TETA_CZECH" 
CREATE EXTENSION dblink;
\c "3644_IRAMUS_MUFFATO_BR" 
CREATE EXTENSION dblink;
\c "3689_LA_ANONIMA_AR" 
CREATE EXTENSION dblink;
\c "3695_METRO_CN" 
CREATE EXTENSION dblink;
\c "3697_LIBERTAD_AR" 
CREATE EXTENSION dblink;
\c "3700_MUELLER_DE" 
CREATE EXTENSION dblink;
\c "3743_COLSUBSIDIO_CO" 
CREATE EXTENSION dblink;
\c "3768_MAKRO_AR" 
CREATE EXTENSION dblink;
\c "1885_LENTA_RU" 
CREATE EXTENSION dblink;
\c "3684_AUCHAN_PL" 
CREATE EXTENSION dblink;
\c "3791_COSMOS_JP" 
CREATE EXTENSION dblink;
\c "93736_CONSUM_SPAIN" 
CREATE EXTENSION dblink;
\c "93641_CONDIS_SPAIN" 
CREATE EXTENSION dblink;
\c "3221_METRO_JEANCOUTU_CA" 
CREATE EXTENSION dblink;
\c "3418_WALTERMART_PH" 
CREATE EXTENSION dblink;
\c "3440_DMART_IN" 
CREATE EXTENSION dblink;
\c "7216_NEW_WORLD_BANNER_NZ" 
CREATE EXTENSION dblink;
\c "7217_PAK_N_SAVE_BANNER_NZ" 
CREATE EXTENSION dblink;
\c "7209_WOOLWORTHS_BANNER_AU" 
CREATE EXTENSION dblink;
\c "SPAR_CROATIA" 
CREATE EXTENSION dblink;
\c "93654_FORNES_SPAIN" 
CREATE EXTENSION dblink;
\c "3809_AEON_JP" 
CREATE EXTENSION dblink;
\c "PNG_NA" 
CREATE EXTENSION dblink;
\c "" 
CREATE EXTENSION dblink;
